const roundtrip = require('./testHelper.js').roundtrip;

describe('examples', function() {

  describe('DependencyFinder', function() {
    it(``, function() { roundtrip(this.test.title) });
    it(`5`, function() { roundtrip(this.test.title) });
    it(`true`, function() { roundtrip(this.test.title) });
    it(`\"hello\" & \"world\"`, function() { roundtrip(this.test.title) });
    it(`A`, function() { roundtrip(this.test.title) });
    it(`Blank()`, function() { roundtrip(this.test.title) });
    it.skip(`5 B`, function() { roundtrip(this.test.title) });
    it.skip(`A As B`, function() { roundtrip(this.test.title) });
    it(`Parent`, function() { roundtrip(this.test.title) });
    it(`Parent.A`, function() { roundtrip(this.test.title) });
    it(`Self`, function() { roundtrip(this.test.title) });
    it(`Self.A`, function() { roundtrip(this.test.title) });
    it.skip(`%placeholder%`, function() { roundtrip(this.test.title) });
    it.skip(`%placeholder%.A`, function() { roundtrip(this.test.title) });
    it.skip(`$\"Hello {\"World\"}\"`, function() { roundtrip(this.test.title) });
    it.skip(`$\"Hello {A}\"`, function() { roundtrip(this.test.title) });
    it.skip(`A;B;C`, function() { roundtrip(this.test.title) });
    it(`[A,B,C]`, function() { roundtrip(this.test.title) });
    it(`A.B`, function() { roundtrip(this.test.title) });
    it(`A.B.C`, function() { roundtrip(this.test.title) });
    it(`If(A)`, function() { roundtrip(this.test.title) });
    it(`If(A, B, C)`, function() { roundtrip(this.test.title) });
    it(`If(A, B, C, D, E).P`, function() { roundtrip(this.test.title) });
    it(`If(A, B, C).Name`, function() { roundtrip(this.test.title) });
    it(`[If(A, B, C).Name,D,E]`, function() { roundtrip(this.test.title) });
    it(`Switch(A)`, function() { roundtrip(this.test.title) });
    it(`Switch(A, B)`, function() { roundtrip(this.test.title) });
    it(`Switch(Slider1.Value, 20, Result1, 10, Result2, 0, Result3)`, function() { roundtrip(this.test.title) });
    it(`Switch(Slider1.Value, 20, Result1, 10, Result2, 0, Result3).Name`, function() { roundtrip(this.test.title) });
    it(`Switch(Slider1.Value, 20, Result1, 10, Result2, 0, Result3, DefaultResult)`, function() { roundtrip(this.test.title) });
    it(`Switch(Slider1.Value, 20, Result1, 10, Result2, 0, Result3, DefaultResult).Name`, function() { roundtrip(this.test.title) });
    it.skip(`If(true, $""Hi"", """")`, function() { roundtrip(this.test.title) });
    it.skip(`If(true, $""{A} {B.Inner}"", """")`, function() { roundtrip(this.test.title) });
    it.skip(`$""{With({ B: 1, C: B.Inner } As Y, Y.C)} {B.Inner}""`, function() { roundtrip(this.test.title) });
    it.skip(`$""{A} {B} {C}""`, function() { roundtrip(this.test.title) });
    it.skip(`$""{With(A, B).Name}""`, function() { roundtrip(this.test.title) });
    it(`With(A).Name`, function() { roundtrip(this.test.title) });
    it.skip(`With({ B: 1, C: B.Inner } As Y, Y.C)`, function() { roundtrip(this.test.title) });
    it(`With(A, B).Name`, function() { roundtrip(this.test.title) });
    it(`With(User, Age + 1)`, function() { roundtrip(this.test.title) });
    it(`With(A, With(B, C))`, function() { roundtrip(this.test.title) });
    it(`With(A, With(B, With(C, D)))`, function() { roundtrip(this.test.title) });
  });

  describe('StructuredCondition', function() {
    it(`Topic.A = 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A > 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A >= 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A < 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A <= 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A <> 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A in \"XA\" `, function() { roundtrip(this.test.title) });
    it(`Topic.A exactin \"XA\"`, function() { roundtrip(this.test.title) });
    it(`IsBlank(Topic.A)`, function() { roundtrip(this.test.title) });
    it(`Not(IsBlank(Topic.A))`, function() { roundtrip(this.test.title) });
    it(`!IsBlank(Topic.A)`, function() { roundtrip(this.test.title) });
    it(`IsEmpty(Topic.A)`, function() { roundtrip(this.test.title) });
    it(`Not(IsEmpty(Topic.A))`, function() { roundtrip(this.test.title) });
    it(`!IsEmpty(Topic.A)`, function() { roundtrip(this.test.title) });
    it(`Topic.A = 5 || Topic.B = 5`, function() { roundtrip(this.test.title) });
    it(`IsEmpty(Topic.A) || !IsEmpty(Topic.B)`, function() { roundtrip(this.test.title) });
    it(`Topic.A = 5 && Topic.B = 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A = 5 Or Topic.B = 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A = 5 And Topic.B = 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A = 5 Or Topic.B = 5 Or Topic.C = 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A = 5 And Topic.B = 5 And Topic.C = 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A = 5 Or Topic.B = 5 And Topic.C = 5`, function() { roundtrip(this.test.title) });
    it(`Topic.A = 5 And Topic.B = 5 Or Topic.C = 5`, function() { roundtrip(this.test.title) });
    it(`(Topic.A = 5 Or Topic.B = 5) And Topic.C = 5`, function() { roundtrip(this.test.title) });
    it.skip(`Topic/*hi*/.A = 5`, function() { roundtrip(this.test.title) });
    it.skip(`/*hi*/Topic.A = 5`, function() { roundtrip(this.test.title) });
    it.skip(`Topic.A = 5/*hi*/`, function() { roundtrip(this.test.title) });
    it.skip(`Topic.A = 5 // hi`, function() { roundtrip(this.test.title) });
    it.skip(`Topic.A = 5 // hi`, function() { roundtrip(this.test.title) });
  });
});
