const roundtrip = require('./testHelper.js').roundtrip;

describe('examples', function() {

  describe('Acumatica', function() {
    it(`RoundUp(Month(Date(2011,5,12))/3,0) & " Q"`, function() { roundtrip(this.test.title) });
    it(`Mid("abc", 2,1)`, function() { roundtrip(this.test.title) });
    it(`Mid("abc", 2)`, function() { roundtrip(this.test.title) });
    it(`Len("abc")`, function() { roundtrip(this.test.title) });
    it(`RoundUp(Month(Date(2011,5,12))/3,0)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2020,3,1), Today()) > 0`, function() { roundtrip(this.test.title) });
    it(`Year(Date(2011,5,12))`, function() { roundtrip(this.test.title) });
    it(`Abs(-5)`, function() { roundtrip(this.test.title) });
    it(`Coalesce("CurrentValue", "DefaultValue")`, function() { roundtrip(this.test.title) });
    it(`Coalesce("", "DefaultValue")`, function() { roundtrip(this.test.title) });
    it(`CountRows([10,30,20,40])`, function() { roundtrip(this.test.title) });
    it.skip(`CountIf([10,50,20,30], Value >= 30 ) // TaxDetails is a child table`, function() { roundtrip(this.test.title) });
    it(`Filter(Table({Name : "Alpha", Discount : 30 }, {Name:"Beta", Discount :45 }), Discount > 40)`, function() { roundtrip(this.test.title) });
  });

  describe('AddColumns', function() {
    it(`AddColumns([1,2,3,4,5], "Double", Value * 2)`, function() { roundtrip(this.test.title) });
    it(`AddColumns([1,2,3,4,5], "Blanks", Blank())`, function() { roundtrip(this.test.title) });
    it(`AddColumns([1,2,0,4,5], "Div", 20/Value)`, function() { roundtrip(this.test.title) });
    it(`AddColumns(Sort([-2, -1, 0, 1, 2], 1 / Value), "Double", Value * 2)`, function() { roundtrip(this.test.title) });
    it(`AddColumns(LastN([1, 2, 3, 4, 5], Blank()), "Double", Value * 2)`, function() { roundtrip(this.test.title) });
  });

  describe('AndOrCases', function() {
    it(`And(1/0 = 7, true)`, function() { roundtrip(this.test.title) });
    it(`Or(1/0 = 7, true)`, function() { roundtrip(this.test.title) });
    it(`And(Blank(), true)`, function() { roundtrip(this.test.title) });
    it(`And(true, true, true, true, Blank(), true)`, function() { roundtrip(this.test.title) });
    it(`Or(Blank(), true)`, function() { roundtrip(this.test.title) });
    it(`And(true)`, function() { roundtrip(this.test.title) });
    it(`Or(false)`, function() { roundtrip(this.test.title) });
    it(`And(true,false)`, function() { roundtrip(this.test.title) });
    it(`true And false`, function() { roundtrip(this.test.title) });
    it(`true && false`, function() { roundtrip(this.test.title) });
    it(`true And true And false`, function() { roundtrip(this.test.title) });
    it(`Or(true,false)`, function() { roundtrip(this.test.title) });
    it(`true Or false`, function() { roundtrip(this.test.title) });
    it(`true||false`, function() { roundtrip(this.test.title) });
    it(`false Or false Or true`, function() { roundtrip(this.test.title) });
    it(`And(true,true,true)`, function() { roundtrip(this.test.title) });
    it(`And(true,true,false)`, function() { roundtrip(this.test.title) });
    it(`Or(false,false,false)`, function() { roundtrip(this.test.title) });
    it(`Or(false,false, true)`, function() { roundtrip(this.test.title) });
    it(`And(false, 1/0=1)`, function() { roundtrip(this.test.title) });
    it(`Or(true, 1/0=1)`, function() { roundtrip(this.test.title) });
  });

  describe('ArgCoercion', function() {
    it(`Char("55")`, function() { roundtrip(this.test.title) });
    it(`Char("Should be Error")`, function() { roundtrip(this.test.title) });
    it(`Char(["55", "56", "57"])`, function() { roundtrip(this.test.title) });
    it(`Char(["55", "Error Coercion", "57"])`, function() { roundtrip(this.test.title) });
    it(`Concatenate(123, "456")`, function() { roundtrip(this.test.title) });
    it(`Concatenate(-1, ["456", "abc"] )`, function() { roundtrip(this.test.title) });
    it(`Concatenate([-1, 123], ["456", "abc"] )`, function() { roundtrip(this.test.title) });
    it(`IsToday(100)`, function() { roundtrip(this.test.title) });
    it(`Len(2345)`, function() { roundtrip(this.test.title) });
    it(`Len([123, -2344566, 0567])`, function() { roundtrip(this.test.title) });
    it(`Day(Average(Date(1900, 1, 2), Date(1900, 1, 4)))`, function() { roundtrip(this.test.title) });
    it(`Day(Average(Date(1900, 2, 28), Date(1900, 3, 1)))`, function() { roundtrip(this.test.title) });
    it(`Day("01-01-2001")`, function() { roundtrip(this.test.title) });
    it(`Day("01-01-2001 1:10:20")`, function() { roundtrip(this.test.title) });
    it(`Hour("01-01-2001 1:10:20")`, function() { roundtrip(this.test.title) });
    it(`Day("abcdef")`, function() { roundtrip(this.test.title) });
    it(`Day(If(false, "hi", Blank()))`, function() { roundtrip(this.test.title) });
    it(`Hour("abcdef")`, function() { roundtrip(this.test.title) });
    it(`Hour(If(false, "hi", Blank()))`, function() { roundtrip(this.test.title) });
  });

  describe('arithmetic', function() {
    it(`1`, function() { roundtrip(this.test.title) });
    it(`1.0`, function() { roundtrip(this.test.title) });
    it(`1.5`, function() { roundtrip(this.test.title) });
    it(`2.0e-4`, function() { roundtrip(this.test.title) });
    it(`1+2`, function() { roundtrip(this.test.title) });
    it(`1 + (1/0)`, function() { roundtrip(this.test.title) });
    it(`1 - (1/0)`, function() { roundtrip(this.test.title) });
    it(`1 * (1/0)`, function() { roundtrip(this.test.title) });
    it(`1 / (1/0)`, function() { roundtrip(this.test.title) });
    it(`5-3`, function() { roundtrip(this.test.title) });
    it(`-3`, function() { roundtrip(this.test.title) });
    it(`-(1/0)`, function() { roundtrip(this.test.title) });
    it(`5 - -3`, function() { roundtrip(this.test.title) });
    it(`-(5+3)`, function() { roundtrip(this.test.title) });
    it(`2*3`, function() { roundtrip(this.test.title) });
    it(`15/3`, function() { roundtrip(this.test.title) });
    it(`1/2`, function() { roundtrip(this.test.title) });
    it(`20%`, function() { roundtrip(this.test.title) });
    it(`200%`, function() { roundtrip(this.test.title) });
    it(`(1/0)%`, function() { roundtrip(this.test.title) });
    it(`1 * 50%`, function() { roundtrip(this.test.title) });
    it(`1+2*3`, function() { roundtrip(this.test.title) });
    it(`1=1`, function() { roundtrip(this.test.title) });
    it(`1<>1`, function() { roundtrip(this.test.title) });
    it(`6>5`, function() { roundtrip(this.test.title) });
    it(`5>6`, function() { roundtrip(this.test.title) });
    it(`5.0>5`, function() { roundtrip(this.test.title) });
    it(`5>=5`, function() { roundtrip(this.test.title) });
    it(`5>=6`, function() { roundtrip(this.test.title) });
    it(`5 < 7`, function() { roundtrip(this.test.title) });
    it(`-5 < 3`, function() { roundtrip(this.test.title) });
    it(`5 < 5`, function() { roundtrip(this.test.title) });
    it(`5 <= 7`, function() { roundtrip(this.test.title) });
    it(`5 < 1/0`, function() { roundtrip(this.test.title) });
    it(`5 <= 1/0`, function() { roundtrip(this.test.title) });
    it(`5 > 1/0`, function() { roundtrip(this.test.title) });
    it(`5 >= 1/0`, function() { roundtrip(this.test.title) });
    it(`5 = 1/0`, function() { roundtrip(this.test.title) });
    it(`5 <> 1/0`, function() { roundtrip(this.test.title) });
  });

  describe('BasicCoercion', function() {
    it(`"Hello " & 42`, function() { roundtrip(this.test.title) });
    it(`42 & "Hello"`, function() { roundtrip(this.test.title) });
    it(`"2" + 3`, function() { roundtrip(this.test.title) });
    it(`"2" + "3"`, function() { roundtrip(this.test.title) });
    it(`"2" * "3"`, function() { roundtrip(this.test.title) });
    it(`("x" * "3")`, function() { roundtrip(this.test.title) });
    it(`true - false`, function() { roundtrip(this.test.title) });
    it(`1 + Blank()`, function() { roundtrip(this.test.title) });
    it(`7 && 0`, function() { roundtrip(this.test.title) });
    it(`0 || 7`, function() { roundtrip(this.test.title) });
    it(`"true" && "anything"`, function() { roundtrip(this.test.title) });
    it(`"anything" || "true"`, function() { roundtrip(this.test.title) });
    it(`true && !Blank()`, function() { roundtrip(this.test.title) });
    it(`Date(2000,1,2) && 1`, function() { roundtrip(this.test.title) });
    it(`If(Date(2000,1,1),1,2)`, function() { roundtrip(this.test.title) });
  });

  describe('Blank', function() {
    it(`If(true, 2,Blank())`, function() { roundtrip(this.test.title) });
    it(`If(false, 2,Blank())`, function() { roundtrip(this.test.title) });
    it(`If(false, Blank(), "hi")`, function() { roundtrip(this.test.title) });
    it(`Blank() - Blank()`, function() { roundtrip(this.test.title) });
    it(`Blank() + Blank()`, function() { roundtrip(this.test.title) });
    it(`-5 < Blank()`, function() { roundtrip(this.test.title) });
    it(`5 < Blank()`, function() { roundtrip(this.test.title) });
    it(`Blank()%`, function() { roundtrip(this.test.title) });
    it(`Blank() =0 `, function() { roundtrip(this.test.title) });
    it(`Blank() <> 0`, function() { roundtrip(this.test.title) });
    it(`0 = Blank()`, function() { roundtrip(this.test.title) });
    it(`0 <> Blank()`, function() { roundtrip(this.test.title) });
    it(`IsBlank(0)`, function() { roundtrip(this.test.title) });
    it(`Blank()`, function() { roundtrip(this.test.title) });
    it(`IsBlank("")`, function() { roundtrip(this.test.title) });
    it(`IsBlank(" ")`, function() { roundtrip(this.test.title) });
    it(`IsBlank(Blank())`, function() { roundtrip(this.test.title) });
    it(`Not(Blank())`, function() { roundtrip(this.test.title) });
    it(`IsBlank(false)`, function() { roundtrip(this.test.title) });
    it(`IsBlank(true)`, function() { roundtrip(this.test.title) });
    it(`IsBlank( If( false, false ) )`, function() { roundtrip(this.test.title) });
    it(`5 + Blank()`, function() { roundtrip(this.test.title) });
    it(`"A" & Blank() & "B"`, function() { roundtrip(this.test.title) });
    it(`Len(Blank()) `, function() { roundtrip(this.test.title) });
    it(`Blank() = Blank()`, function() { roundtrip(this.test.title) });
    it(`Blank() = ""`, function() { roundtrip(this.test.title) });
    it(`Blank() <> ""`, function() { roundtrip(this.test.title) });
    it(`IsBlank(Blank() + Blank())`, function() { roundtrip(this.test.title) });
    it.skip(`Blank(`, function() { roundtrip(this.test.title) });
  });

  describe('Boolean', function() {
    it(`Boolean("true")`, function() { roundtrip(this.test.title) });
    it(`Boolean("false")`, function() { roundtrip(this.test.title) });
    it(`Boolean("x")`, function() { roundtrip(this.test.title) });
    it(`Boolean(" true")`, function() { roundtrip(this.test.title) });
    it(`Boolean(" false")`, function() { roundtrip(this.test.title) });
    it(`Boolean("True")`, function() { roundtrip(this.test.title) });
    it(`Boolean("False")`, function() { roundtrip(this.test.title) });
    it(`Boolean(Text(Blank()))`, function() { roundtrip(this.test.title) });
    it(`Boolean(Text(0/1))`, function() { roundtrip(this.test.title) });
    it(`Boolean("0")`, function() { roundtrip(this.test.title) });
    it(`Boolean(0)`, function() { roundtrip(this.test.title) });
    it(`Boolean([])`, function() { roundtrip(this.test.title) });
    it(`Boolean(true)`, function() { roundtrip(this.test.title) });
    it(`Boolean(false)`, function() { roundtrip(this.test.title) });
  });

  describe('Coalesce', function() {
    it(`Coalesce( Blank(), 1 )`, function() { roundtrip(this.test.title) });
    it(`Coalesce( "", "x" )`, function() { roundtrip(this.test.title) });
    it(`Coalesce( Blank(), "", Blank(), "", "3", "4" )`, function() { roundtrip(this.test.title) });
    it(`Coalesce("")`, function() { roundtrip(this.test.title) });
    it(`Coalesce( 5, 1/0 )`, function() { roundtrip(this.test.title) });
    it(`Coalesce(false,true)`, function() { roundtrip(this.test.title) });
    it(`Coalesce(true,false)`, function() { roundtrip(this.test.title) });
    it(`Coalesce(Blank())`, function() { roundtrip(this.test.title) });
    it(`Coalesce(Blank(), 1/0, 10)`, function() { roundtrip(this.test.title) });
  });

  describe('Concat', function() {
    it(`Concat(ForAll(["a","b","c"], With({x:Value}, x)), Value)`, function() { roundtrip(this.test.title) });
    it.skip(`Concat(ForAll(["a","b","c"] As x, With({x:"hide"}, x)), Value)`, function() { roundtrip(this.test.title) });
    it.skip(`Concat(ForAll(["a","b","c"] As x, With({y:"hide"}, x)), Value)`, function() { roundtrip(this.test.title) });
    it(`Concat(["A", "B", "C"], ThisRecord.Value)`, function() { roundtrip(this.test.title) });
    it.skip(`Concat(["A", "B", "C"] As X, X.Value)`, function() { roundtrip(this.test.title) });
    it(`Concat(["A", "B", "C"], Value)`, function() { roundtrip(this.test.title) });
    it.skip(`Concat(ForAll(["A","B"] As X,Concat(ForAll(["C","D"] As Y,X.Value&Y.Value),Value)),Value)`, function() { roundtrip(this.test.title) });
    it.skip(`Concat(`, function() { roundtrip(this.test.title) });
    it(`Concat(ForAll(["A", "B"], ThisRecord), Value)`, function() { roundtrip(this.test.title) });
    it.skip(`Concat(`, function() { roundtrip(this.test.title) });
    it(`Concat(ForAll(FirstN([60, 61, 62, 63, 64], Blank()), Char(Value)), Value)`, function() { roundtrip(this.test.title) });
    it(`Concat(ForAll(Sort([60, 61, 0, 63, 64], 1/Value), Char(Value)), Value)`, function() { roundtrip(this.test.title) });
  });

  describe('Concatenate', function() {
    it(`Concatenate("777", ["abc"], ["1", "2"])`, function() { roundtrip(this.test.title) });
    it(`Concatenate("777", Filter(["empty table"], Value <> Value), ["1", "2"])`, function() { roundtrip(this.test.title) });
  });

  describe('CountFunctions', function() {
    it(`CountRows([1, 2, 3, 4, 5])`, function() { roundtrip(this.test.title) });
    it(`CountRows(Blank())`, function() { roundtrip(this.test.title) });
    it(`CountRows(Sort([-2, -1, 0, 1, 2], 1 / Value))`, function() { roundtrip(this.test.title) });
    it(`CountRows([1, 2, 1/0, 4, 5])`, function() { roundtrip(this.test.title) });
    it(`CountIf([1, 2, 3, 4, 5], Value > 2)`, function() { roundtrip(this.test.title) });
    it(`CountIf(LastN([1,2,3,4], Blank()), Value > 2)`, function() { roundtrip(this.test.title) });
    it(`CountIf(Sort([-2, -1, 0, 1, 2], 1 / Value), Value > 2)`, function() { roundtrip(this.test.title) });
    it(`CountIf([1, 2, 0, 4, 5], 1/Value > 2)`, function() { roundtrip(this.test.title) });
    it(`CountIf([1, 2, 3, 4], 123)`, function() { roundtrip(this.test.title) });
  });

  describe('Date', function() {
    it(`Date(-1, 2, 3)`, function() { roundtrip(this.test.title) });
    it(`Date(Blank(), 2, 3)`, function() { roundtrip(this.test.title) });
    it(`Date(80, 1, 2)`, function() { roundtrip(this.test.title) });
    it(`Date(2000, 25, 69)`, function() { roundtrip(this.test.title) });
    it(`Date(2000, 2, -1)`, function() { roundtrip(this.test.title) });
    it(`Date(2000, -2, 1)`, function() { roundtrip(this.test.title) });
    it(`Date(2000, -2, -1)`, function() { roundtrip(this.test.title) });
    it(`Month(Date(2011,5,12))`, function() { roundtrip(this.test.title) });
    it(`Year(Date(2011,5,12))`, function() { roundtrip(this.test.title) });
    it(`Day(Date(2011,5,12))`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30))`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(-1, 2, 3), Date(2011,1,30))`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(Blank(), 2, 3), Date(2011,1,30))`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15), Date(Blank(), 2, 3))`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), Blank())`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2013,1,15) , Date(2012,1,30))`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), TimeUnit.Days)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), "Days")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), "days")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), "DaYs")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2013,1,15) , Date(2012,1,30), TimeUnit.Days)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), "milliseconds")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), "seconds")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), "minutes")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), "hours")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), "quarters")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,7,30), "quarters")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), TimeUnit.Milliseconds)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), TimeUnit.Seconds)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), TimeUnit.Minutes)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), TimeUnit.Hours)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,1,30), TimeUnit.Quarters)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2011,1,15) , Date(2011,7,30), TimeUnit.Quarters)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2021,1,1), Date(2000,1,1), TimeUnit.Years)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2021,1,1), Date(2000,1,1), "Years")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2021,1,1), Date(2021,2,1), TimeUnit.Months)`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2021,1,1), Date(2021,2,1), "Months")`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Date(2021,1,1), Date(2021,1,20), TimeUnit.Months)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2012,2,28), 1)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2013,2,28), 1)`, function() { roundtrip(this.test.title) });
    it(`Day(DateAdd(Date(2012,2,28), 1))`, function() { roundtrip(this.test.title) });
    it(`Month(DateAdd(Date(2013,2,28), 1))`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,15) < Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,15) < Date(2011,1,15)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,15) <= Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,15) <= Date(2011,1,15)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,30) < Date(2011,1,15)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,30) <= Date(2011,1,15)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,15) > Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,15) > Date(2011,1,15)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,15) >= Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,15) >= Date(2011,1,15)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,30) > Date(2011,1,15)`, function() { roundtrip(this.test.title) });
    it(`Date(2011,1,30) >= Date(2011,1,15)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 3) < DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 3) < DateAdd(Date(2011,1,15), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 3) <= DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 3) <= DateAdd(Date(2011,1,15), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,30), 3) < DateAdd(Date(2011,1,15), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,30), 3) <= DateAdd(Date(2011,1,15), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 3) > DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 3) > DateAdd(Date(2011,1,15), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 3) >= DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 3) >= DateAdd(Date(2011,1,15), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,30), 3) > DateAdd(Date(2011,1,15), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,30), 3) >= DateAdd(Date(2011,1,15), 3)`, function() { roundtrip(this.test.title) });
    it(`Date(Blank(), 2, 3) < Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(Blank(), 2, 3) <= Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(Blank(), 2, 3) > Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(Blank(), 2, 3) >= Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(Blank(), 2, 3), 3) < DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(Blank(), 2, 3), 3) <= DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(Blank(), 2, 3), 3) > DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(Blank(), 2, 3), 3) >= DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`Date(1/0, 2, 3) < Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(1/0, 2, 3) <= Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(1/0, 2, 3) > Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`Date(1/0, 2, 3) >= Date(2011,1,30)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(1/0, 2, 3), 3) < DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(1/0, 2, 3), 3) <= DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(1/0, 2, 3), 3) > DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(1/0, 2, 3), 3) >= DateAdd(Date(2011,1,30), 3)`, function() { roundtrip(this.test.title) });
    it(`Date(2001,2,14) = Date(2001,2,14)`, function() { roundtrip(this.test.title) });
    it(`Day(DateAdd(Date(2001,1,1), 3))`, function() { roundtrip(this.test.title) });
    it(`Day(DateAdd(Date(2001,1,1), 3, Blank()))`, function() { roundtrip(this.test.title) });
    it(`Day(DateAdd(Date(2001,1,1), Blank()))`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(-1, 2, 3), 3)`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(Blank(), 2, 3), 3)`, function() { roundtrip(this.test.title) });
    it(`Day(DateAdd(Date(2001,1,1), 4, TimeUnit.Days))`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 100000000, "milliseconds")`, function() { roundtrip(this.test.title) });
    it(`DateAdd(Date(2011,1,15), 100000000, TimeUnit.Milliseconds)`, function() { roundtrip(this.test.title) });
    it(`Day(Date(2011,1,15) + 1)`, function() { roundtrip(this.test.title) });
    it(`Day(1 + Date(2011,1,15))`, function() { roundtrip(this.test.title) });
    it(`Day(Date(2011,1,15) - 1)`, function() { roundtrip(this.test.title) });
    it(`Day((Date(2011,1,15) + 1) + 1)`, function() { roundtrip(this.test.title) });
    it(`Day((1 + Date(2011,1,15)) + 1)`, function() { roundtrip(this.test.title) });
    it(`Day((Date(2011,1,15) - 1) - 1)`, function() { roundtrip(this.test.title) });
    it(`Day(Date(-1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Day(Blank())`, function() { roundtrip(this.test.title) });
    it(`Month(DateAdd(Date(2001,1,1), 12, TimeUnit.Months))`, function() { roundtrip(this.test.title) });
    it(`Month(DateAdd(Date(2001,1,1), 3, TimeUnit.Quarters))`, function() { roundtrip(this.test.title) });
    it(`Month(DateAdd(Date(2001,1,1), 3, "Quarters"))`, function() { roundtrip(this.test.title) });
    it(`Month(DateAdd(Date(2001,1,1), 3, "quarters"))`, function() { roundtrip(this.test.title) });
    it(`Month(DateAdd(Date(2001,1,1), 3, "quaRTers"))`, function() { roundtrip(this.test.title) });
    it(`Month(Date(-1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Month(Blank())`, function() { roundtrip(this.test.title) });
    it(`Year(DateAdd(Date(2001,1,1), 1, TimeUnit.Years))`, function() { roundtrip(this.test.title) });
    it(`Year(Date(-1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Year(Blank())`, function() { roundtrip(this.test.title) });
    it(`Date(2001, 2, 14) + 2`, function() { roundtrip(this.test.title) });
  });

  describe('DateValue', function() {
    it(`Text(DateTimeValue("01-01-2001 1:10:20"))`, function() { roundtrip(this.test.title) });
    it(`Date(2001, 2, 14) = DateValue("2001-02-14")`, function() { roundtrip(this.test.title) });
    it(`DateValue("02-14-01") = DateValue("02/14/01")`, function() { roundtrip(this.test.title) });
    it(`DateValue("02/14/2001") = DateValue("2001-02-14")`, function() { roundtrip(this.test.title) });
    it(`Hour(DateAdd(DateAdd(DateTimeValue("01-01-2001 1:10:20"), TimeZoneOffset(), TimeUnit.Minutes), -TimeZoneOffset(), "Minutes"))`, function() { roundtrip(this.test.title) });
    it(`Second(DateAdd(DateTimeValue("01-01-2001 1:10:20"), 1, "Seconds"))`, function() { roundtrip(this.test.title) });
    it(`Hour(DateAdd(DateTimeValue("01-01-2001 1:10:20"), 1, TimeUnit.Hours))`, function() { roundtrip(this.test.title) });
    it(`Minute(DateAdd(DateTimeValue("01-01-2001 1:10:20"), 1, TimeUnit.Minutes))`, function() { roundtrip(this.test.title) });
    it(`Text(DateTimeValue("02/14/2001 6:00 AM") - 0.5)`, function() { roundtrip(this.test.title) });
    it(`Text(DateTimeValue("02/14/2001 6:00 AM") + 0.0417)`, function() { roundtrip(this.test.title) });
    it(`Text(DateTimeValue("02/14/2001 6:00 AM") + 7e-4)`, function() { roundtrip(this.test.title) });
    it(`Second(DateTimeValue("02/14/2001 6:00 AM") - 1.1574e-5)`, function() { roundtrip(this.test.title) });
  });

  describe('Equality', function() {
    it(`1 = 1`, function() { roundtrip(this.test.title) });
    it(`1 <> 1`, function() { roundtrip(this.test.title) });
    it(`1 = 2`, function() { roundtrip(this.test.title) });
    it(`1 <> 2`, function() { roundtrip(this.test.title) });
    it(`true = true`, function() { roundtrip(this.test.title) });
    it(`true = false`, function() { roundtrip(this.test.title) });
    it(`true <> true`, function() { roundtrip(this.test.title) });
    it(`true <> false`, function() { roundtrip(this.test.title) });
    it(`1.0 = 1.0`, function() { roundtrip(this.test.title) });
    it(`1.0 <> 1.0`, function() { roundtrip(this.test.title) });
    it(`1.0 <> 1.1`, function() { roundtrip(this.test.title) });
    it(`1.0 = 1.1`, function() { roundtrip(this.test.title) });
    it(`"foo" = "foo"`, function() { roundtrip(this.test.title) });
    it(`"foo" <> "foo"`, function() { roundtrip(this.test.title) });
    it(`"foo" = "bar"`, function() { roundtrip(this.test.title) });
    it(`"foo" <> "bar"`, function() { roundtrip(this.test.title) });
    it(`Date(2022,2,17) = Date(2022,2,17)`, function() { roundtrip(this.test.title) });
    it(`Date(2022,2,17) <> Date(2022,2,17)`, function() { roundtrip(this.test.title) });
    it(`Date(2022,2,17) = Date(2017,4,27)`, function() { roundtrip(this.test.title) });
    it(`Date(2022,2,17) <> Date(2017,4,27)`, function() { roundtrip(this.test.title) });
    it(`10% = 10%`, function() { roundtrip(this.test.title) });
    it(`10% = 0.1`, function() { roundtrip(this.test.title) });
    it(`10% <> 12%`, function() { roundtrip(this.test.title) });
    it(`10% = 0.12`, function() { roundtrip(this.test.title) });
    it(`Time(10,30,00) = Time(10,30,00)`, function() { roundtrip(this.test.title) });
    it(`Time(14,20,30) = Time(2,30,30)`, function() { roundtrip(this.test.title) });
    it(`Time(10,30,00) <> Time(10,30,00)`, function() { roundtrip(this.test.title) });
    it(`Time(14,20,30) <> Time(2,30,30)`, function() { roundtrip(this.test.title) });
  });

  describe('Error', function() {
    it(`1/0`, function() { roundtrip(this.test.title) });
    it(`Sqrt(-1)`, function() { roundtrip(this.test.title) });
    it(`IsError(1/0)`, function() { roundtrip(this.test.title) });
    it(`IsError(1)`, function() { roundtrip(this.test.title) });
    it(`IsError(Error({Kind: ErrorKind.Validation}))`, function() { roundtrip(this.test.title) });
    it(`IsError(Error({Kind: 11}))`, function() { roundtrip(this.test.title) });
    it(`Error({Kind:ErrorKind.InvalidArgument})`, function() { roundtrip(this.test.title) });
    it(`Error({Kind:ErrorKind.Validation})`, function() { roundtrip(this.test.title) });
    it.skip(`Error({Kind:Validation}) // We need to use the fully-qualified enum value`, function() { roundtrip(this.test.title) });
    it.skip(`Error({Kind:"Validation"}) // Error kind needs to be numeric!`, function() { roundtrip(this.test.title) });
    it(`IfError(1/0, Error({Kind:FirstError.Kind}))`, function() { roundtrip(this.test.title) });
    it(`IfError(1/0, 3)`, function() { roundtrip(this.test.title) });
    it(`IfError(1/0, FirstError.Kind)`, function() { roundtrip(this.test.title) });
    it(`IfError(Error({Kind:12}), FirstError.Kind)`, function() { roundtrip(this.test.title) });
    it(`IfError(0, 1, Sqrt(-2), 2)`, function() { roundtrip(this.test.title) });
    it.skip(`IfError(0, 1, Error({Kind: ErrorKind.Unknown}), 2)`, function() { roundtrip(this.test.title) });
    it(`IfError(1, 2)`, function() { roundtrip(this.test.title) });
    it(`IfError(1, 2, 3)`, function() { roundtrip(this.test.title) });
    it(`IfError(1, 2, 3, 4)`, function() { roundtrip(this.test.title) });
    it(`IsBlank(1/0)`, function() { roundtrip(this.test.title) });
    it.skip(`Not(IsBlank(1/0))`, function() { roundtrip(this.test.title) });
    it(`"Result: " & IfError(1/0, -1)`, function() { roundtrip(this.test.title) });
    it(`"Result: " & IfError(1, "error 1", 2, "error 2", "no error")`, function() { roundtrip(this.test.title) });
    it(`"Result: " & IfError({a:1, b:"hello"}, {a:2, b:"error"}).b`, function() { roundtrip(this.test.title) });
    it(`"Result: " & IfError(1, {a:1}, 2, {a:2}, {a:3}).a`, function() { roundtrip(this.test.title) });
    it(`"Result: " & IfError({a:{a1:true},b:"hello"}, {a:1,b:"error 1"}, {a:{a1:{a2:3}},b:"world"}, {a:1,b:"error 2"}, {a:1,b:"valid"}, {a:1,b:"error 3"}).a`, function() { roundtrip(this.test.title) });
  });

  describe('FilterFunctions', function() {
    it.skip(`Filter([1,2,3] As X, X.Value > 2)`, function() { roundtrip(this.test.title) });
    it(`Filter([1,2,3], Value >= 2)`, function() { roundtrip(this.test.title) });
    it(`Filter([1,2,3], ThisRecord.Value >= 2)`, function() { roundtrip(this.test.title) });
    it(`irst([1,4,2,7]).Value`, function() { roundtrip(this.test.title) });
    it(`First([30,20,10,40])`, function() { roundtrip(this.test.title) });
    it(`Last([30,20,10,40])`, function() { roundtrip(this.test.title) });
    it(`FirstN([30,20,10,40],2)`, function() { roundtrip(this.test.title) });
    it(`LastN([30,20,10,40],3)`, function() { roundtrip(this.test.title) });
    it(`Filter([1,4,2,7], Value > 2)`, function() { roundtrip(this.test.title) });
    it(`First(Filter([1,4,2,7], Value > 2)).Value`, function() { roundtrip(this.test.title) });
    it(`Filter([1,2,0,3,4], 1/ThisRecord.Value >= 0)`, function() { roundtrip(this.test.title) });
    it(`Filter([1,2,0,3,4], Blank())`, function() { roundtrip(this.test.title) });
    it(`Filter(LastN([1,2,3,4], Blank()), 1/ThisRecord.Value >= 0)`, function() { roundtrip(this.test.title) });
    it(`Filter(Blank(), Blank())`, function() { roundtrip(this.test.title) });
    it(`Filter(Sort([-2, -1, 0, 1, 2], 1 / Value), 1/ThisRecord.Value >= 0)`, function() { roundtrip(this.test.title) });
  });

  describe('Find', function() {
    it(`Find("", "")`, function() { roundtrip(this.test.title) });
    it(`Find("", "", 1)`, function() { roundtrip(this.test.title) });
    it(`Find("", "", 2)`, function() { roundtrip(this.test.title) });
    it(`Find("", "textToBeSearchedIn")`, function() { roundtrip(this.test.title) });
    it(`Find("", "textToBeSearchedIn", 1)`, function() { roundtrip(this.test.title) });
    it(`Find("", "textToBeSearchedIn", 4)`, function() { roundtrip(this.test.title) });
    it(`Find("textToFind", "")`, function() { roundtrip(this.test.title) });
    it(`Find("textToFind", "", 2)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,FirstName")`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,FirstName", 2)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,FirstName", 9)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,FirstName", 9.5)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,FirstName", 10)`, function() { roundtrip(this.test.title) });
    it(`Find("#", "LastName,FirstName")`, function() { roundtrip(this.test.title) });
    it(`Find("#", "LastName,FirstName", 3)`, function() { roundtrip(this.test.title) });
    it(`Find("#", "LastName,FirstName", 100)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,First,Name")`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,First,Name", 2)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,First,Name", 9)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,First,Name", 10)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastNameFirstName,")`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastNameFirstName,", 18)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastNameFirstName,", 19)`, function() { roundtrip(this.test.title) });
    it(`Find("MULTIPLECHARS", "LastNameMULTIPLECHARSFirstName")`, function() { roundtrip(this.test.title) });
    it(`Find("MULTIPLECHARS", "LastNameMULTIPLEFirstName")`, function() { roundtrip(this.test.title) });
    it(`Find(",", ",,,,,,")`, function() { roundtrip(this.test.title) });
    it(`Find(",", ",,,,,,", 2)`, function() { roundtrip(this.test.title) });
    it(`Find(Blank(), Blank())`, function() { roundtrip(this.test.title) });
    it(`Find(Blank(), Blank(), 2)`, function() { roundtrip(this.test.title) });
    it(`Find(Blank(), "textToBeSearchedIn")`, function() { roundtrip(this.test.title) });
    it(`Find(Blank(), "textToBeSearchedIn", 2)`, function() { roundtrip(this.test.title) });
    it(`Find("textToFind", Blank())`, function() { roundtrip(this.test.title) });
    it(`Find("textToFind", Blank(), 3)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,FirstName", -1)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,FirstName", 0)`, function() { roundtrip(this.test.title) });
    it(`Find(",", "LastName,FirstName", Blank())`, function() { roundtrip(this.test.title) });
    it(`Find("B", "LastNameisBlah")`, function() { roundtrip(this.test.title) });
    it(`Find("B", "LastNameisblah")`, function() { roundtrip(this.test.title) });
    it(`Find("b", "LastNameisblah")`, function() { roundtrip(this.test.title) });
    it(`Find("b", "LastNameisBlah")`, function() { roundtrip(this.test.title) });
    it(`Find("BB", "LastNameisBBlah")`, function() { roundtrip(this.test.title) });
    it(`Find("BB", "LastNameisBblah")`, function() { roundtrip(this.test.title) });
    it(`Find("bb", "LastNameisbblah")`, function() { roundtrip(this.test.title) });
    it(`Find("bb", "LastNameisbBlah")`, function() { roundtrip(this.test.title) });
    it(`Find("B", "LastNameisBlahFirstNameisBlah")`, function() { roundtrip(this.test.title) });
    it(`Find("B", "LastNameisBlahFirstNameisBlah", 2)`, function() { roundtrip(this.test.title) });
    it(`Find("B", "LastNameisBlahFirstNameisBlah", 11)`, function() { roundtrip(this.test.title) });
    it(`Find("B", "LastNameisBlahFirstNameisBlah", 12)`, function() { roundtrip(this.test.title) });
    it(`Find("B", "LastNameisBlahFirstNameisblah", 12)`, function() { roundtrip(this.test.title) });
  });

  describe('FindT', function() {
    it(`Find(Blank(), [""], [1])`, function() { roundtrip(this.test.title) });
    it(`Find([""], [""], Blank())`, function() { roundtrip(this.test.title) });
    it(`Find(If(false, ["blank table"], Blank()), If(false, ["blank table"], Blank()), [1])`, function() { roundtrip(this.test.title) });
    it(`Find(If(false, ["blank table"], Blank()), If(false, ["blank table"], Blank()), [2])`, function() { roundtrip(this.test.title) });
    it(`Find(If(false, ["blank table"], Blank()), "textToBeSearchedIn", [5])`, function() { roundtrip(this.test.title) });
    it(`Find("textToSearch", If(false, ["blank table"], Blank()), [1])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), "", ","], If(false, ["blank table"], Blank()), 1)`, function() { roundtrip(this.test.title) });
    it(`Find(["b"], ["abc", "cde"])`, function() { roundtrip(this.test.title) });
    it(`Find(["b"], ["abc", "cde"], If(false, [0], Blank()))`, function() { roundtrip(this.test.title) });
    it(`Find(["b"], ["abc", "cde"], Filter([0], Value <> Value))`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), "", ","], If(false, ["blank table"], Blank()), [1, 2, 3])`, function() { roundtrip(this.test.title) });
    it(`Find(If(false, ["blank table"], Blank()), [Blank(), "", "textToBeSearchedIn"], 1)`, function() { roundtrip(this.test.title) });
    it(`Find(If(false, ["blank table"], Blank()), [Blank(), "", "textToBeSearchedIn"], [1, 2, 3])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), "", ","], "textToBeSearchedIn,textToBeSearchedIn", 1)`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), "", ",", ","], "textToBeSearchedIn,textToBeSearchedIn", [1, 2, 3, 20])`, function() { roundtrip(this.test.title) });
    it(`Find(",", ["textToBeSearchedIn,textToBeSearchedIn"], 1)`, function() { roundtrip(this.test.title) });
    it(`Find(",", ["textToBeSearchedIn,textToBeSearchedIn", "textToBeSearchedIn,textToBeSearchedIn,", "textToBeSearchedIn,textToBeSearchedIn"], [1, 20, 40])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), "", ","], ["textToBeSearchedIn,textToBeSearchedIn", "textToBeSearchedIn,textToBeSearchedIn,", "textToBeSearchedIn,textToBeSearchedIn"], [1, 10, 9])`, function() { roundtrip(this.test.title) });
    it(`Find(",", "textToBeSearchedIn,textToBeSearchedIn", [1, 2, 19, 20])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), "", ","], If(false, ["blank table"], Blank()))`, function() { roundtrip(this.test.title) });
    it(`Find(If(false, ["blank table"], Blank()), [Blank(), "", "textToBeSearchedIn"])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), "", ","], "textToBeSearchedIn,textToBeSearchedIn")`, function() { roundtrip(this.test.title) });
    it(`Find(",", ["textToBeSearchedIn,textToBeSearchedIn"])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), "", ","], ["textToBeSearchedIn,textToBeSearchedIn", "textToBeSearchedIn,textToBeSearchedIn,", "textToBeSearchedIn,textToBeSearchedIn"])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), ","], ["lastName,firstName", "lastName,firstName,", "lastName,firstName", Blank()])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), ",", "", "findMe"], [Blank(), "lastName,firstName"])`, function() { roundtrip(this.test.title) });
    it.skip(`Find([Blank(), ","], ["lastName,firstName",], [9, 2, 3])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), ",", "", "findMe"], [Blank(), "lastName,firstName"], 10)`, function() { roundtrip(this.test.title) });
    it(`Find([",", Blank()], "lastName,firstName", [1, 2, 3])`, function() { roundtrip(this.test.title) });
    it(`Find(",", [Blank(), "lastName,firstName", "lastName,firstName"], [1, 2])`, function() { roundtrip(this.test.title) });
    it(`Find(Filter(["empty table"], Value <> Value), "", 1)`, function() { roundtrip(this.test.title) });
    it(`Find("", Filter(["empty table"], Value <> Value), 1)`, function() { roundtrip(this.test.title) });
    it(`Find("textToFind", Filter(["empty table"], Value <> Value), 2)`, function() { roundtrip(this.test.title) });
    it(`Find(Filter(["empty table"], Value <> Value), Filter(["empty table"], Value <> Value))`, function() { roundtrip(this.test.title) });
    it(`Find(Filter(["empty table"], Value <> Value), Filter(["empty table"], Value <> Value), Filter(["empty table"], Value <> Value))`, function() { roundtrip(this.test.title) });
    it(`Find(Filter(["empty table"], Value <> Value), [Blank(), "lastName,firstName", "lastName,firstName"], 2)`, function() { roundtrip(this.test.title) });
    it(`Find(Filter(["empty table"], Value <> Value), "textToSearch", [1, 2])`, function() { roundtrip(this.test.title) });
    it(`Find([",", Blank(), ""], Filter(["empty table"], Value <> Value), 2)`, function() { roundtrip(this.test.title) });
    it(`Find(",", Filter(["empty table"], Value <> Value), [1, 1])`, function() { roundtrip(this.test.title) });
    it(`Find([Blank(), ",", "", "findMe"], [Blank(), "lastName,firstName", "lastName,firstName"], Filter(["empty table"], Value <> Value))`, function() { roundtrip(this.test.title) });
    it(`Find(",", [Blank(), "lastName,firstName"], Filter(["empty table"], Value <> Value))`, function() { roundtrip(this.test.title) });
    it(`Find("c", Table({ within: "abc" }, { within: Error({Kind: ErrorKind.Validation}) }, { within: "cde" }))`, function() { roundtrip(this.test.title) });
    it(`Find("c", ["abc", Error({Kind: ErrorKind.Validation}), "cde"])`, function() { roundtrip(this.test.title) });
    it(`Find(Table({ find: "a" }, { find: Error({Kind: ErrorKind.Validation}) }, { find: "b" }), "abc")`, function() { roundtrip(this.test.title) });
    it(`Find(["a", Error({Kind: ErrorKind.Validation}), "b"], "abc")`, function() { roundtrip(this.test.title) });
    it(`Find(Table({ find: "a" }, { find: Mid("Hello", -1) }, { find: "b" }, If(1/0>2, { find: "e" }), { find: "c" }), Table({ within: "abc" }, If(Sqrt(-1)<0, { within: "err" }), { within: Left("err", -1) }, If(Right("err", -3) = "err", { within: "err" }), { within: "abc" }))`, function() { roundtrip(this.test.title) });
    it(`Find(Table({ find: "a" }, { find: "b" }, { find: "c" }), If(1/0>2,"abcdef"))`, function() { roundtrip(this.test.title) });
    it(`Find(If(Sqrt(-1)<0,"First second third"), Table({ within: "First" }, { within: "Second" }))`, function() { roundtrip(this.test.title) });
  });

  describe('First', function() {
    it(`First([1, 2, 3, 4, 5])`, function() { roundtrip(this.test.title) });
    it(`First(Blank())`, function() { roundtrip(this.test.title) });
    it(`First([1, 1/0, 3])`, function() { roundtrip(this.test.title) });
    it(`First([1/0, 2, 3]).Value`, function() { roundtrip(this.test.title) });
    it(`First(Sort([-2, -1, 0, 1, 2], 1 / Value))`, function() { roundtrip(this.test.title) });
    it(`FirstN([1, 2, 3, 4, 5], 2)`, function() { roundtrip(this.test.title) });
    it(`FirstN([1, 2, 3, 4, 5], 1)`, function() { roundtrip(this.test.title) });
    it(`FirstN([1, 2, 3, 4, 5])`, function() { roundtrip(this.test.title) });
    it(`FirstN([1, 2, 3, 4, 5], 6)`, function() { roundtrip(this.test.title) });
    it(`FirstN([1, 2, 3, 4, 5], -1)`, function() { roundtrip(this.test.title) });
    it(`FirstN([1, 2, 3, 4, 5], Blank())`, function() { roundtrip(this.test.title) });
    it(`FirstN(Blank(), 2)`, function() { roundtrip(this.test.title) });
    it(`FirstN(Blank())`, function() { roundtrip(this.test.title) });
    it(`FirstN(Sort([-2, -1, 0, 1, 2], 1 / Value), 2)`, function() { roundtrip(this.test.title) });
    it(`FirstN([1, 2, 3, 4, 5], 1/0)`, function() { roundtrip(this.test.title) });
    it(`First(Table({a:1,b:2},{c:3})).c`, function() { roundtrip(this.test.title) });
    it(`First(LastN(Table({a:"1", b:"101"}, {a:"2"}, {a:"3"}), 1)).b`, function() { roundtrip(this.test.title) });
    it(`First(Table({a:{aa:11,ab:12},b:1},{a:{ac:23},b:2})).a.ac`, function() { roundtrip(this.test.title) });
    it(`First(Table({a:{aa:11,ab:12},b:1},{a:{ac:23},b:2})).a.aa`, function() { roundtrip(this.test.title) });
    it(`First(Table({a:{Value:2},b:1},{a:{Value:1},b:2})).a`, function() { roundtrip(this.test.title) });
    it(`First(First(Table({a:{aa:11,ab:12,ad:Table({aaa:1},{aaa:2})},b:1},{a:{ac:23,ad:Table({bbb:1},{bbb:2})},b:2})).a.ad).bbb`, function() { roundtrip(this.test.title) });
    it(`First(First(Table({a:{aa:11,ab:12,ad:Table({aaa:1},{aaa:2})},b:1},{a:{ac:23,ad:Table({bbb:1},{bbb:2})},b:2})).a.ad).aaa`, function() { roundtrip(this.test.title) });
    it(`First(Filter([1,2,3],Value=4)).Value`, function() { roundtrip(this.test.title) });
    it(`FirstN(Filter([1,2,3],Value=4),2)`, function() { roundtrip(this.test.title) });
  });

  describe('ForAll', function() {
    it(`ForAll([1,2,3], ThisRecord)`, function() { roundtrip(this.test.title) });
    it(`ForAll([1,2,3], ThisRecord.Value)`, function() { roundtrip(this.test.title) });
    it.skip(`ForAll([1,2,3] As X, X)`, function() { roundtrip(this.test.title) });
    it.skip(`ForAll([1,2,3] As X, X.Value)`, function() { roundtrip(this.test.title) });
    it(`ForAll([1,2,3],Value*Value)`, function() { roundtrip(this.test.title) });
    it.skip(`First(ForAll([1,2,3] As X, X)).Value`, function() { roundtrip(this.test.title) });
    it.skip(`First(ForAll([1,2,3] As X, X.Value)).Value`, function() { roundtrip(this.test.title) });
    it(`ForAll(Sort([60, 61, 62, 63, 64], 1/Value), Char(Value))`, function() { roundtrip(this.test.title) });
    it(`ForAll(FirstN([60, 61, 62, 63, 64], Blank()), Char(Value))`, function() { roundtrip(this.test.title) });
    it(`ForAll(Sort([60, 61, 0, 63, 64], 1/Value), Char(Value))`, function() { roundtrip(this.test.title) });
    it(`ForAll(Table({Value:1,Zulu:1}, {Value:0,Zulu:0}, {Value:2,Zulu:2}), 1/ThisRecord.Value)`, function() { roundtrip(this.test.title) });
    it(`First(LastN(ForAll(Table({Value:1,Zulu:1}, {Value:0,Zulu:0}, {Value:2,Zulu:2}), 1/ThisRecord.Value), 2)).Value`, function() { roundtrip(this.test.title) });
    it(`Table({Value:1},First(LastN(ForAll(Table({Value:1,Zulu:1}, {Value:0,Zulu:0}, {Value:2,Zulu:2}), 1/ThisRecord.Value), 2)),{Value:2})`, function() { roundtrip(this.test.title) });
    it(`First(First(LastN(ForAll(Table({Value:1}, {Value:0}, {Value:2}), Table({a: 1/ThisRecord.Value})), 2)).Value)`, function() { roundtrip(this.test.title) });
  });

  describe('If', function() {
    it(`If(5>10,1/0,99)`, function() { roundtrip(this.test.title) });
    it(`If(10>5,99,1/0=1,98)`, function() { roundtrip(this.test.title) });
    it(`If(true, If(false,1,2), 3)`, function() { roundtrip(this.test.title) });
    it(`If(true, 1)`, function() { roundtrip(this.test.title) });
    it(`If(false, 1)`, function() { roundtrip(this.test.title) });
    it(`If(false, true)`, function() { roundtrip(this.test.title) });
    it(`If(false, 1, 2)`, function() { roundtrip(this.test.title) });
    it(`If(true, 1, 2)`, function() { roundtrip(this.test.title) });
    it(`If(false, 1, true, 2)`, function() { roundtrip(this.test.title) });
    it(`If(false, 1, false, 2)`, function() { roundtrip(this.test.title) });
    it(`If(false, 1, false, 2, 3)`, function() { roundtrip(this.test.title) });
    it(`If(false && true, false && true, false && true, false && true, false && true)`, function() { roundtrip(this.test.title) });
    it(`If(1 > 2 || 1 = 0 || 1 <> 1 || 2 < 1 || 3 <= 2 || 2 >= 3 || !true || (!false && false), "foo")`, function() { roundtrip(this.test.title) });
    it(`If(false, "3", 2)`, function() { roundtrip(this.test.title) });
    it(`If(true, "3", 2)`, function() { roundtrip(this.test.title) });
    it(`If(false, 3, "2")`, function() { roundtrip(this.test.title) });
    it(`If(Blank(), 3, "2")`, function() { roundtrip(this.test.title) });
    it(`If(1/0 = 7, 2, 3)`, function() { roundtrip(this.test.title) });
  });

  describe('inScalar', function() {
    it(`("a" & 1/0) in "abc"`, function() { roundtrip(this.test.title) });
    it(`"a" in ("abc" & 1/0)`, function() { roundtrip(this.test.title) });
    it(`"e" in "applE"`, function() { roundtrip(this.test.title) });
    it(`"e" exactin "applE"`, function() { roundtrip(this.test.title) });
    it(`"x y" exactin "abx yz"`, function() { roundtrip(this.test.title) });
    it(`"*" in "apple"`, function() { roundtrip(this.test.title) });
    it(`"x" in "apple"`, function() { roundtrip(this.test.title) });
    it(`"" in "apple"`, function() { roundtrip(this.test.title) });
    it(`"" in ""`, function() { roundtrip(this.test.title) });
    it(`Blank() in Blank()`, function() { roundtrip(this.test.title) });
    it(`If(false, "", Blank()) in "abc"`, function() { roundtrip(this.test.title) });
    it(`"" in If(false, Blank(), "")`, function() { roundtrip(this.test.title) });
    it(`"" in If(true, Blank(), "")`, function() { roundtrip(this.test.title) });
    it(`5 in "5"`, function() { roundtrip(this.test.title) });
    it(`6 in "5"`, function() { roundtrip(this.test.title) });
    it(`1+2 in "3"`, function() { roundtrip(this.test.title) });
    it(`"1+2" in "3"`, function() { roundtrip(this.test.title) });
    it(`"[[]" in "SQL literal ["`, function() { roundtrip(this.test.title) });
    it(`"[[]" in "SQL literal [[]"`, function() { roundtrip(this.test.title) });
    it(`"[']" in "SQL literal '"`, function() { roundtrip(this.test.title) });
    it(`"[']" in "SQL literal [']"`, function() { roundtrip(this.test.title) });
    it(`"'" in "SQL literal '"`, function() { roundtrip(this.test.title) });
  });

  describe('inTable', function() {
    it(`2 in [1,2,3]`, function() { roundtrip(this.test.title) });
    it(`4 in [1,2,3]`, function() { roundtrip(this.test.title) });
    it(`1/0 in [1,2,3]`, function() { roundtrip(this.test.title) });
    it(`true in [false, true]`, function() { roundtrip(this.test.title) });
    it(`true in [false, false]`, function() { roundtrip(this.test.title) });
    it(`"a" in ["aa" ]`, function() { roundtrip(this.test.title) });
    it(`"a" in ["b", "a" ]`, function() { roundtrip(this.test.title) });
    it(`"A" in ["b", "a" ]`, function() { roundtrip(this.test.title) });
    it(`"A" exactin ["b", "a" ]`, function() { roundtrip(this.test.title) });
    it(`"A" exactin ["b", "A" ]`, function() { roundtrip(this.test.title) });
    it(`"" in ["aa" ]`, function() { roundtrip(this.test.title) });
    it(`"" in ["" ]`, function() { roundtrip(this.test.title) });
    it(`If(false,2,Blank()) in [1, Blank(), 2]`, function() { roundtrip(this.test.title) });
    it(`Blank() in [1, Blank(), 2] `, function() { roundtrip(this.test.title) });
    it(`3 in [1, Blank(), 2]`, function() { roundtrip(this.test.title) });
    it(`2 in Table({a:1}, {a:2}, {a:3})`, function() { roundtrip(this.test.title) });
    it(`"hello" exactin Table({Result:"Hello"},{Result:"World"})`, function() { roundtrip(this.test.title) });
  });

  describe('IsBlankOrError', function() {
    it(`IsBlankOrError(If(1 < 0, "hello"))`, function() { roundtrip(this.test.title) });
    it(`IsBlankOrError("hello")`, function() { roundtrip(this.test.title) });
    it(`IsBlankOrError(If(1 / 0 < 2, "hello"))`, function() { roundtrip(this.test.title) });
  });

  describe('IsNumeric', function() {
    it(`sNumeric("A")`, function() { roundtrip(this.test.title) });
    it(`sNumeric(123)`, function() { roundtrip(this.test.title) });
    it(`sNumeric(-123)`, function() { roundtrip(this.test.title) });
    it(`sNumeric(-123.1)`, function() { roundtrip(this.test.title) });
    it(`sNumeric(123.1)`, function() { roundtrip(this.test.title) });
    it(`sNumeric("1" + 2)`, function() { roundtrip(this.test.title) });
    it(`sNumeric(1/0)`, function() { roundtrip(this.test.title) });
    it(`sNumeric(Blank())`, function() { roundtrip(this.test.title) });
    it(`sNumeric({RecordValue: 123})`, function() { roundtrip(this.test.title) });
    it(`sNumeric([1,2,3,4])`, function() { roundtrip(this.test.title) });
  });

  describe('IsToday', function() {
    it(`IsToday(Today())`, function() { roundtrip(this.test.title) });
    it(`IsToday(Now())`, function() { roundtrip(this.test.title) });
    it(`IsToday(Date(-1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`IsToday(Date(Blank(), 2, 3))`, function() { roundtrip(this.test.title) });
    it(`IsToday(Date(2012,1,1))`, function() { roundtrip(this.test.title) });
    it(`IsToday(DateAdd(Today(),-1))`, function() { roundtrip(this.test.title) });
    it(`DateDiff(Now(), Today(), TimeUnit.Minutes) <> 0`, function() { roundtrip(this.test.title) });
    it(`Date(Year(Today()), Month(Today()), Day(Today())) = Today()`, function() { roundtrip(this.test.title) });
  });

  describe('Last', function() {
    it(`Last([1, 2, 3, 4, 5])`, function() { roundtrip(this.test.title) });
    it(`Last(Blank())`, function() { roundtrip(this.test.title) });
    it(`Last([1, 1/0, 3])`, function() { roundtrip(this.test.title) });
    it(`Last([1, 2, 1/0]).Value`, function() { roundtrip(this.test.title) });
    it(`Last(Sort([-2, -1, 0, 1, 2], 1 / Value))`, function() { roundtrip(this.test.title) });
    it(`LastN([1, 2, 3, 4, 5], 2)`, function() { roundtrip(this.test.title) });
    it(`LastN([1, 2, 3, 4, 5])`, function() { roundtrip(this.test.title) });
    it(`LastN([1, 2, 3, 4, 5], 6)`, function() { roundtrip(this.test.title) });
    it(`LastN([1, 2, 3, 4, 5], -1)`, function() { roundtrip(this.test.title) });
    it(`LastN([1, 2, 3, 4, 5], Blank())`, function() { roundtrip(this.test.title) });
    it(`LastN(Blank(), 2)`, function() { roundtrip(this.test.title) });
    it(`LastN(Blank())`, function() { roundtrip(this.test.title) });
    it(`LastN(Sort([-2, -1, 0, 1, 2], 1 / Value), 2)`, function() { roundtrip(this.test.title) });
    it(`LastN([1, 2, 3, 4, 5], 1/0)`, function() { roundtrip(this.test.title) });
    it(`LastN(Table({a:1, b:101}, {a:2}, {a:3}), 2)`, function() { roundtrip(this.test.title) });
    it(`LastN(Table({a:1}, {a:2}, {a:3}), 2)`, function() { roundtrip(this.test.title) });
    it(`LastN(Table({Value:1,Zulu:1}, {Value:2,Zulu:2}, {Value:3,Zulu:3}), 2)`, function() { roundtrip(this.test.title) });
    it(`Last(Filter([1,2,3],Value=4)).Value`, function() { roundtrip(this.test.title) });
    it(`LastN(Filter([1,2,3],Value=4),2)`, function() { roundtrip(this.test.title) });
  });

  describe('literals', function() {
    it(`1.0`, function() { roundtrip(this.test.title) });
    it(`"abc"`, function() { roundtrip(this.test.title) });
    it(`{b : 2, a: 1}`, function() { roundtrip(this.test.title) });
    it(`[1,4,2,7]`, function() { roundtrip(this.test.title) });
    it(`Table({b:1,a:2},{a:4,b:3})`, function() { roundtrip(this.test.title) });
  });

  describe('Log', function() {
    it(`Log(100)`, function() { roundtrip(this.test.title) });
    it(`Log(0)`, function() { roundtrip(this.test.title) });
    it(`Log(Blank())`, function() { roundtrip(this.test.title) });
    it(`Log(1/0)`, function() { roundtrip(this.test.title) });
  });

  describe('mathfuncs', function() {
    it(`Average(1,0,5)`, function() { roundtrip(this.test.title) });
    it.skip(`Average("1",0,5) // coerce`, function() { roundtrip(this.test.title) });
    it(`Average(Blank())`, function() { roundtrip(this.test.title) });
    it(`Average(1,Blank(),5)`, function() { roundtrip(this.test.title) });
    it(`Sum(1,2)`, function() { roundtrip(this.test.title) });
    it(`Sum(1)`, function() { roundtrip(this.test.title) });
    it(`Sum(0)`, function() { roundtrip(this.test.title) });
    it(`Sqrt(4)+1`, function() { roundtrip(this.test.title) });
    it(`Mod(7,3)`, function() { roundtrip(this.test.title) });
    it(`Mod(Blank(),3)`, function() { roundtrip(this.test.title) });
    it(`Mod(7,Blank())`, function() { roundtrip(this.test.title) });
    it(`Mod(7,1/0)`, function() { roundtrip(this.test.title) });
    it(`Mod(1/0,3)`, function() { roundtrip(this.test.title) });
    it(`Mod(1, 0)`, function() { roundtrip(this.test.title) });
    it(`Abs(-5)`, function() { roundtrip(this.test.title) });
    it(`Abs(5)`, function() { roundtrip(this.test.title) });
    it(`Abs(0)`, function() { roundtrip(this.test.title) });
    it(`Abs(Blank())`, function() { roundtrip(this.test.title) });
    it(`Abs(1/0)`, function() { roundtrip(this.test.title) });
    it(`Text(Exp(Ln(2)), "#")`, function() { roundtrip(this.test.title) });
    it(`Text(Ln(Exp(2)), "#")`, function() { roundtrip(this.test.title) });
    it(`Ln(0)`, function() { roundtrip(this.test.title) });
    it(`Ln(Blank())`, function() { roundtrip(this.test.title) });
    it(`Ln(1/0)`, function() { roundtrip(this.test.title) });
    it(`IsError(Ln(0))`, function() { roundtrip(this.test.title) });
    it(`Power(2, 3)`, function() { roundtrip(this.test.title) });
    it(`Sqrt(Power(5.5, 2))`, function() { roundtrip(this.test.title) });
    it(`Sqrt(0)`, function() { roundtrip(this.test.title) });
    it(`Sqrt(Blank())`, function() { roundtrip(this.test.title) });
    it(`Sqrt(1/0)`, function() { roundtrip(this.test.title) });
    it(`Power(2, -2)`, function() { roundtrip(this.test.title) });
    it(`Power(Blank(), -2)`, function() { roundtrip(this.test.title) });
    it(`Power(1/0, -2)`, function() { roundtrip(this.test.title) });
    it(`Round(Exp(2), 2)`, function() { roundtrip(this.test.title) });
    it(`Exp(Blank())`, function() { roundtrip(this.test.title) });
    it(`Exp(1/0)`, function() { roundtrip(this.test.title) });
    it.skip(`2^3`, function() { roundtrip(this.test.title) });
    it.skip(`2^-2`, function() { roundtrip(this.test.title) });
    it(`Max(Blank(), 100, -5, "2000", Value("2001"), Text(2002))`, function() { roundtrip(this.test.title) });
    it(`Min(-100, If(true, -1000, 200))`, function() { roundtrip(this.test.title) });
    it(`Round(1.5, 0)`, function() { roundtrip(this.test.title) });
    it(`Round(2.1, 0)`, function() { roundtrip(this.test.title) });
    it(`Round(1.95, 1)`, function() { roundtrip(this.test.title) });
    it(`Round(225, -2)`, function() { roundtrip(this.test.title) });
    it(`Round(225, -3)`, function() { roundtrip(this.test.title) });
    it(`Round(550, -3)`, function() { roundtrip(this.test.title) });
    it(`Round(550, -4)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(1.1, 0)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(0, 0)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(2.2222, 2)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(1.99, 3)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(88, -1)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(88, -4)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(Blank(), 0)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(Blank(), 2)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(1.1, Blank())`, function() { roundtrip(this.test.title) });
    it(`RoundUp(Blank(), Blank())`, function() { roundtrip(this.test.title) });
    it(`RoundUp(1.1, 1/0)`, function() { roundtrip(this.test.title) });
    it(`RoundUp(1/0, 0)`, function() { roundtrip(this.test.title) });
    it(`RoundDown(1.9, 0)`, function() { roundtrip(this.test.title) });
    it(`RoundDown(2.111, 2)`, function() { roundtrip(this.test.title) });
    it(`RoundDown(2.111, Blank())`, function() { roundtrip(this.test.title) });
    it(`RoundDown(Blank(), 2)`, function() { roundtrip(this.test.title) });
    it(`RoundDown(Blank(), Blank())`, function() { roundtrip(this.test.title) });
    it(`RoundDown(699, -2)`, function() { roundtrip(this.test.title) });
    it(`RoundDown(2.111, 1/0)`, function() { roundtrip(this.test.title) });
    it(`RoundDown(1/0, 2)`, function() { roundtrip(this.test.title) });
    it(`Trunc(2.111, 2)`, function() { roundtrip(this.test.title) });
    it(`Trunc(2.111)`, function() { roundtrip(this.test.title) });
    it(`Trunc(2.111, Blank())`, function() { roundtrip(this.test.title) });
    it(`Trunc(Blank())`, function() { roundtrip(this.test.title) });
    it(`Trunc(Blank(), 2)`, function() { roundtrip(this.test.title) });
    it(`Trunc(Blank(), Blank())`, function() { roundtrip(this.test.title) });
    it(`Trunc(1.1, 1/0)`, function() { roundtrip(this.test.title) });
    it(`Trunc(1/0, 0)`, function() { roundtrip(this.test.title) });
    it(`Trunc(1/0)`, function() { roundtrip(this.test.title) });
    it(`Int(4.1)`, function() { roundtrip(this.test.title) });
    it(`Int(-4.1)`, function() { roundtrip(this.test.title) });
    it(`Int(Blank())`, function() { roundtrip(this.test.title) });
    it(`Int(1/0)`, function() { roundtrip(this.test.title) });
  });

  describe('OptionSet', function() {
    it(`OptionSet.Option1 <> OptionSet.Option2`, function() { roundtrip(this.test.title) });
    it(`OptionSet.Option2 = OptionSet.Option2`, function() { roundtrip(this.test.title) });
    it(`"Coerces to " & OptionSet.Option2`, function() { roundtrip(this.test.title) });
    it(`OtherOptionSet.OptionD & "Coerces"`, function() { roundtrip(this.test.title) });
    it(`If(TopOptionSetField = OptionSet.Option1, "success", "failure")`, function() { roundtrip(this.test.title) });
    it(`Switch(Nested.InnerOtherOptionSet, OtherOptionSet.OptionA, 1, OtherOptionSet.OptionB, 2, OtherOptionSet.OptionC, 3, OtherOptionSet.OptionD, 4)`, function() { roundtrip(this.test.title) });
    it(`OtherOptionSet.OptionA <> TopOptionSetField`, function() { roundtrip(this.test.title) });
    it(`IsBlank(Nested.InnerOtherOptionSet)`, function() { roundtrip(this.test.title) });
    it(`IsBlank(If(1 < 0, TopOptionSetField))`, function() { roundtrip(this.test.title) });
    it(`IsBlankOrError(Nested.InnerOtherOptionSet)`, function() { roundtrip(this.test.title) });
    it(`IsBlankOrError(If(1 < 0, Nested.InnerOtherOptionSet))`, function() { roundtrip(this.test.title) });
    it(`IsBlankOrError(If(1 / 0 < 2, TopOptionSetField))`, function() { roundtrip(this.test.title) });
  });

  describe('ParseJson', function() {
    it(`Value(Index(ParseJson("[5]"), 1))`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("5"))`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("true"))`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("false"))`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("""5"""))`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("""a"""))`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("null"))`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("{""a"": 5}").a)`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("{""a"": 5, ""A"": 10}").a)`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("{""a"": 5, ""A"": 10}").A)`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("{""a"": 5}").b)`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("""s""").a)`, function() { roundtrip(this.test.title) });
    it(`Value(ParseJson("This "" Is , "" Invalid ").a)`, function() { roundtrip(this.test.title) });
    it(`Text(Index(ParseJson("[""s""]"), 1))`, function() { roundtrip(this.test.title) });
    it(`Text(ParseJson("""s"""))`, function() { roundtrip(this.test.title) });
    it(`Text(ParseJson("null"))`, function() { roundtrip(this.test.title) });
    it(`Text(ParseJson("true"))`, function() { roundtrip(this.test.title) });
    it(`Text(ParseJson("false"))`, function() { roundtrip(this.test.title) });
    it(`Text(ParseJson("5"))`, function() { roundtrip(this.test.title) });
    it(`Boolean(ParseJson("true"))`, function() { roundtrip(this.test.title) });
    it(`Boolean(ParseJson("false"))`, function() { roundtrip(this.test.title) });
    it(`ParseJson("{""a"": null}").a`, function() { roundtrip(this.test.title) });
    it(`ParseJson("{""a"": null}").a.b`, function() { roundtrip(this.test.title) });
    it(`ParseJson("null").a`, function() { roundtrip(this.test.title) });
    it(`ParseJson("null").a.b`, function() { roundtrip(this.test.title) });
    it(`ParseJson("{}").a`, function() { roundtrip(this.test.title) });
    it(`ParseJson("{}").a.b`, function() { roundtrip(this.test.title) });
    it(`Sum(Table(ParseJson("[1, 2, 3, 4, 5]")), Value(Value))`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") + ParseJson("5")`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") - ParseJson("5")`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") * ParseJson("5")`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") / ParseJson("5")`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") = ParseJson("5")`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") > ParseJson("5")`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") < ParseJson("5")`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") <> ParseJson("5")`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") >= ParseJson("5")`, function() { roundtrip(this.test.title) });
    it(`ParseJson("5") <= ParseJson("5")`, function() { roundtrip(this.test.title) });
  });

  describe('Rand', function() {
    it(`andBetween(1, 1)`, function() { roundtrip(this.test.title) });
    it(`sError(RandBetween(5, 1))`, function() { roundtrip(this.test.title) });
    it(`andBetween(Blank(),1)`, function() { roundtrip(this.test.title) });
    it(`sError(RandBetween(1/0, 1))`, function() { roundtrip(this.test.title) });
    it(`sError(RandBetween(0, 1/0))`, function() { roundtrip(this.test.title) });
    it(`andBetween(100.5, 100.7)`, function() { roundtrip(this.test.title) });
    it(`Sum(Sequence(100), With({RandomNumber: RandBetween(1,20)}, If(RandomNumber >=1 && RandomNumber <= 20, 1, 0)))`, function() { roundtrip(this.test.title) });
    it(`Sum(Sequence(100), With({RandomNumber: RandBetween(2-1,50-30)}, If(RandomNumber >=1 && RandomNumber <= 20, 1, 0)))`, function() { roundtrip(this.test.title) });
    it(`Sum(Sequence(100), With({RandomNumber: Rand()}, If(RandomNumber > 0 && RandomNumber < 1.0, 1, 0)))`, function() { roundtrip(this.test.title) });
  });

  describe('Record', function() {
    it(`If(true, {x:2},Blank()).x`, function() { roundtrip(this.test.title) });
    it(`IsBlank(If(false, {x:2},Blank()).x)`, function() { roundtrip(this.test.title) });
    it(`With({x:Blank()}, x*x)`, function() { roundtrip(this.test.title) });
    it(`IsBlank({})`, function() { roundtrip(this.test.title) });
    it(`IsBlank({ x : Blank(), y : 2}.x)`, function() { roundtrip(this.test.title) });
  });

  describe('Sequence', function() {
    it(`Sequence(4)`, function() { roundtrip(this.test.title) });
    it(`Sequence(4,24)`, function() { roundtrip(this.test.title) });
    it(`Sequence(4,4,-1)`, function() { roundtrip(this.test.title) });
    it(`Sequence(4,-100,0.5)`, function() { roundtrip(this.test.title) });
    it(`Sequence(.9)`, function() { roundtrip(this.test.title) });
    it(`Sequence(Blank())`, function() { roundtrip(this.test.title) });
    it(`Sequence(4,Blank())`, function() { roundtrip(this.test.title) });
    it(`Sequence(4,24,Blank())`, function() { roundtrip(this.test.title) });
    it(`Sequence(1/0)`, function() { roundtrip(this.test.title) });
    it(`Sequence(4,1/0)`, function() { roundtrip(this.test.title) });
    it(`Sequence(4,4,1/0)`, function() { roundtrip(this.test.title) });
  });

  describe('Sort', function() {
    it(`Sort([-2, -1, 5, 1, 2], Value)`, function() { roundtrip(this.test.title) });
    it(`Sort([-2, -1, 5, 1, 2], Value, SortOrder.Descending)`, function() { roundtrip(this.test.title) });
    it(`Sort([-2, Blank(), 5, 1, 2], Value)`, function() { roundtrip(this.test.title) });
    it(`Sort([-2, Blank(), 5, 1, 2], Value, SortOrder.Descending)`, function() { roundtrip(this.test.title) });
    it(`Sort([-2, -1, 0, 1, 2], 1 / Value)`, function() { roundtrip(this.test.title) });
    it(`Sort(["a", "b", "D", "x", "J", "C"], Value)`, function() { roundtrip(this.test.title) });
    it(`Sort(["a", "b", "D", "x", "J", "C"], Value, SortOrder.Descending)`, function() { roundtrip(this.test.title) });
    it(`Sort(["a", "b", Blank(), "x", "J", "C"], Value)`, function() { roundtrip(this.test.title) });
    it(`Sort(["a", "b", Blank(), "x", "J", "C"], Value, SortOrder.Descending)`, function() { roundtrip(this.test.title) });
    it(`Sort([true,false,true,false,true], Value)`, function() { roundtrip(this.test.title) });
    it(`Sort([true,false,true,false,true], Value, SortOrder.Descending)`, function() { roundtrip(this.test.title) });
    it(`Sort([true,false,Blank(),false,true], Value)`, function() { roundtrip(this.test.title) });
    it(`Sort([true,false,Blank(),false,true], Value, SortOrder.Descending)`, function() { roundtrip(this.test.title) });
    it(`First(LastN(Sort([-2, -1, 0, 1, 2], 1 / Value), 3)).Value`, function() { roundtrip(this.test.title) });
  });

  describe('Split', function() {
    it(`Split("this is a test", " ")`, function() { roundtrip(this.test.title) });
    it(`Split("test", "")`, function() { roundtrip(this.test.title) });
    it(`Split("Hello world", If(1 < 0, ""))`, function() { roundtrip(this.test.title) });
    it(`Split( "Hello, World", "l" )`, function() { roundtrip(this.test.title) });
    it(`Split( "Hello, World", "ll" )`, function() { roundtrip(this.test.title) });
    it(`Split( "Hello, World", "%" )`, function() { roundtrip(this.test.title) });
    it(`Split( "Hello, World", "," )`, function() { roundtrip(this.test.title) });
    it(`Split("", "")`, function() { roundtrip(this.test.title) });
    it(`Split(If(1 < 0, ""), "")`, function() { roundtrip(this.test.title) });
    it(`Split(Text(1/0), "")`, function() { roundtrip(this.test.title) });
  });

  describe('string', function() {
    it(`"foo"`, function() { roundtrip(this.test.title) });
    it(`""`, function() { roundtrip(this.test.title) });
    it(`Left("foo", 1)`, function() { roundtrip(this.test.title) });
    it(`Left(Text(100), If(true, 1, 0))`, function() { roundtrip(this.test.title) });
    it(`Left("foo", 100)`, function() { roundtrip(this.test.title) });
    it(`Left("foo", 0)`, function() { roundtrip(this.test.title) });
    it(`Left("foo", -1)`, function() { roundtrip(this.test.title) });
    it(`Left("foo", 1/0)`, function() { roundtrip(this.test.title) });
    it(`Left(Blank(), 1)`, function() { roundtrip(this.test.title) });
    it(`Left("foo", Blank())`, function() { roundtrip(this.test.title) });
    it(`Right("bar", 1)`, function() { roundtrip(this.test.title) });
    it(`Right(Text(false), 3-2)`, function() { roundtrip(this.test.title) });
    it(`Right("bar", 77)`, function() { roundtrip(this.test.title) });
    it(`Right("bar", 0)`, function() { roundtrip(this.test.title) });
    it(`Right("bar", -1)`, function() { roundtrip(this.test.title) });
    it(`Right("foo", 1/0)`, function() { roundtrip(this.test.title) });
    it(`Right(Blank(), 1)`, function() { roundtrip(this.test.title) });
    it(`Right("foo", Blank())`, function() { roundtrip(this.test.title) });
    it(`Mid("foobar", 2, 3)`, function() { roundtrip(this.test.title) });
    it(`Mid("foobar", 3)`, function() { roundtrip(this.test.title) });
    it(`Mid("abcdef", 3.1, 1.9)`, function() { roundtrip(this.test.title) });
    it(`Mid("foo" & "bar", If(false, 1, 2), 8/4)`, function() { roundtrip(this.test.title) });
    it(`Mid("foo", 100)`, function() { roundtrip(this.test.title) });
    it(`Mid("bar", -1)`, function() { roundtrip(this.test.title) });
    it(`IsError(Mid("bar", -1))`, function() { roundtrip(this.test.title) });
    it(`Mid("bar", 2, -1)`, function() { roundtrip(this.test.title) });
    it(`IsError(Mid("bar", 2, -1))`, function() { roundtrip(this.test.title) });
    it(`Mid("foo", 0)`, function() { roundtrip(this.test.title) });
    it(`Mid(Text(1/0, "#.000"), 1)`, function() { roundtrip(this.test.title) });
    it(`IsError(Mid("foo", 0))`, function() { roundtrip(this.test.title) });
    it(`Mid("foo", 1, 0)`, function() { roundtrip(this.test.title) });
    it(`IsError(Mid("foo", 2, 0))`, function() { roundtrip(this.test.title) });
    it(`Len("foo")`, function() { roundtrip(this.test.title) });
    it(`Len("foo" & "bar")`, function() { roundtrip(this.test.title) });
    it(`Len(If(true, "foo", "bar!"))`, function() { roundtrip(this.test.title) });
    it(`Len(Blank())`, function() { roundtrip(this.test.title) });
    it(`Len(Text(1/0, "#.000"))`, function() { roundtrip(this.test.title) });
    it(`"f" in "foo"`, function() { roundtrip(this.test.title) });
    it(`"f" in "FOO"`, function() { roundtrip(this.test.title) });
    it(`"F" in "foo"`, function() { roundtrip(this.test.title) });
    it(`"yes" in "no"`, function() { roundtrip(this.test.title) });
    it(`"A" exactin "BAR"`, function() { roundtrip(this.test.title) });
    it(`"a" exactin "BAR"`, function() { roundtrip(this.test.title) });
    it(`"A" exactin "bar"`, function() { roundtrip(this.test.title) });
    it(`StartsWith("foo", "f")`, function() { roundtrip(this.test.title) });
    it(`StartsWith("FOO", "f")`, function() { roundtrip(this.test.title) });
    it(`StartsWith("FOO", "O")`, function() { roundtrip(this.test.title) });
    it(`StartsWith("foo", "")`, function() { roundtrip(this.test.title) });
    it(`StartsWith("foo", Blank())`, function() { roundtrip(this.test.title) });
    it(`StartsWith("foobar", Text(1/0))`, function() { roundtrip(this.test.title) });
    it(`EndsWith("foobar", "bar")`, function() { roundtrip(this.test.title) });
    it(`EndsWith("foobar", "foo")`, function() { roundtrip(this.test.title) });
    it(`EndsWith("foobar", "")`, function() { roundtrip(this.test.title) });
    it(`EndsWith("foobar", Blank())`, function() { roundtrip(this.test.title) });
    it(`EndsWith("foobar", Text(1/0))`, function() { roundtrip(this.test.title) });
    it(`TrimEnds("   Hello     World   ")`, function() { roundtrip(this.test.title) });
    it(`TrimEnds(Blank())`, function() { roundtrip(this.test.title) });
    it(`TrimEnds(Text(1/0))`, function() { roundtrip(this.test.title) });
    it(`Trim("   Hello     World   ")`, function() { roundtrip(this.test.title) });
    it(`Trim(Blank())`, function() { roundtrip(this.test.title) });
    it(`Trim(Text(1/0))`, function() { roundtrip(this.test.title) });
    it(`Lower("E. E. Cummings")`, function() { roundtrip(this.test.title) });
    it(`Lower(Blank())`, function() { roundtrip(this.test.title) });
    it(`Lower(Text(1/0, "000"))`, function() { roundtrip(this.test.title) });
    it(`Upper("Important!")`, function() { roundtrip(this.test.title) });
    it(`Upper(Blank())`, function() { roundtrip(this.test.title) });
    it(`Upper(Text(1/0, "000"))`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", "xx")`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", "xx", 2)`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", "xx", Len("ab") + 1)`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "xx", "yy", 1)`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", "xx", 4)`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", "xx", 1/0)`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", "xx", 0)`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", "xx", Blank())`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", Blank(), "xx")`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", Blank(), "xx", 2)`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", Blank())`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", Blank(), 2)`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "", "xx")`, function() { roundtrip(this.test.title) });
    it(`IsError(Substitute("abcabcabc", "ab", "xx", 0))`, function() { roundtrip(this.test.title) });
    it(`Substitute("abcabcabc", "ab", "xx", -2)`, function() { roundtrip(this.test.title) });
    it(`IsError(Substitute("abcabcabc", "ab", "xx", -2))`, function() { roundtrip(this.test.title) });
    it(`Replace("abcabcabc", 4, 2, "xx")`, function() { roundtrip(this.test.title) });
    it(`Replace("abcabcabc", 200, 240, "xx")`, function() { roundtrip(this.test.title) });
    it(`Replace("abcabcabc", 200, 2, "xx")`, function() { roundtrip(this.test.title) });
    it(`Replace("abcabcabc", 4, 240, "xx")`, function() { roundtrip(this.test.title) });
    it(`Replace("abcabcabc", 0, 0, "xx")`, function() { roundtrip(this.test.title) });
    it(`IsError(Replace("abcabcabc", 0, 0, "xx"))`, function() { roundtrip(this.test.title) });
    it(`Replace("abcabcabc", 1, -2, "xx")`, function() { roundtrip(this.test.title) });
    it(`IsError(Replace("abcabcabc", 1, -2, "xx"))`, function() { roundtrip(this.test.title) });
    it(`Replace("abcabcabc", -1, -2, "xx")`, function() { roundtrip(this.test.title) });
    it(`IsError(Replace("abcabcabc", -1, -2, "xx"))`, function() { roundtrip(this.test.title) });
    it(`Concatenate("a", "b", Text(7))`, function() { roundtrip(this.test.title) });
    it(`Concatenate("a", "b", Blank())`, function() { roundtrip(this.test.title) });
    it(`Concatenate(Text(1/0, "000"), "b", Text(7))`, function() { roundtrip(this.test.title) });
  });

  describe.skip('StringInterpolate', function() {
    it(`$"Hello {"World!"}"`, function() { roundtrip(this.test.title) });
    it(`$"Hello {"World!"} 2"`, function() { roundtrip(this.test.title) });
    it(`$"One {$"Two {"Three"}"} Four"`, function() { roundtrip(this.test.title) });
    it(`$"This string {{{"has"}}} curly braces"`, function() { roundtrip(this.test.title) });
    it(`$"This string {{ has }} curly braces"`, function() { roundtrip(this.test.title) });
    it(`"This string {{ has }} curly braces"`, function() { roundtrip(this.test.title) });
    it(`$""`, function() { roundtrip(this.test.title) });
    it(`$"Hello"`, function() { roundtrip(this.test.title) });
    it(`$"{123}"`, function() { roundtrip(this.test.title) });
    it(`$"{123}{456}"`, function() { roundtrip(this.test.title) });
    it(`$"{"`, function() { roundtrip(this.test.title) });
    it(`$"}"`, function() { roundtrip(this.test.title) });
    it(`$"{" & ""`, function() { roundtrip(this.test.title) });
    it(`$"}" & ""`, function() { roundtrip(this.test.title) });
    it(`$"{`, function() { roundtrip(this.test.title) });
    it(`$"}`, function() { roundtrip(this.test.title) });
    it(`$"{1}{2}{{3{{4{{5{{6{{7"`, function() { roundtrip(this.test.title) });
    it(`$"{{"`, function() { roundtrip(this.test.title) });
    it(`$"{{a}}"`, function() { roundtrip(this.test.title) });
    it(`$"-{{a}}-"`, function() { roundtrip(this.test.title) });
    it(`$"-{{a}}"`, function() { roundtrip(this.test.title) });
    it(`$"{{a}}-"`, function() { roundtrip(this.test.title) });
    it(`$"! {Date(1980,1,1)} !"`, function() { roundtrip(this.test.title) });
    it(`$""""`, function() { roundtrip(this.test.title) });
    it(`""""`, function() { roundtrip(this.test.title) });
    it(`$"! {With({a:4,b:6},a*b)} !"`, function() { roundtrip(this.test.title) });
    it(`$"! {With({array:[1,5,9]},Sum(Sequence(CountRows(array)) As Index,Power(Last(FirstN(array,Index.Value)).Value, Index.Value)))} !"`, function() { roundtrip(this.test.title) });
    it(`$"! {$"{$"{true}"}"} !"`, function() { roundtrip(this.test.title) });
    it(`$"! !"`, function() { roundtrip(this.test.title) });
    it(`$"! "" !"`, function() { roundtrip(this.test.title) });
    it(`$"! {{1,2}} !"`, function() { roundtrip(this.test.title) });
    it(`$"! {[1,2]} !"`, function() { roundtrip(this.test.title) });
    it(`$"! {Table({a:1})} !"`, function() { roundtrip(this.test.title) });
    it(`$"! {{a:1,b:2}} !"`, function() { roundtrip(this.test.title) });
    it(`$"! { {a:1,b:2} } !"`, function() { roundtrip(this.test.title) });
    it(`$"Hello {"`, function() { roundtrip(this.test.title) });
    it(`$"Hello {}"`, function() { roundtrip(this.test.title) });
  });

  describe('switch', function() {
    it(`Switch(1,1,"a")`, function() { roundtrip(this.test.title) });
    it(`Switch(99,1,"a")`, function() { roundtrip(this.test.title) });
    it(`Switch(99,1,"a","default")`, function() { roundtrip(this.test.title) });
    it(`Switch(2,1,"a", 2,"b")`, function() { roundtrip(this.test.title) });
    it(`Switch(99,1,"a", 2,"b")`, function() { roundtrip(this.test.title) });
    it(`Switch(99,1,"a", 2,"b", "default")`, function() { roundtrip(this.test.title) });
    it(`Switch(99,1,1/0,99,7)`, function() { roundtrip(this.test.title) });
    it(`Switch(99,1,8,99,7,1/0,9)`, function() { roundtrip(this.test.title) });
    it(`Switch(If(true,1,2),7-8,true && false, !false)`, function() { roundtrip(this.test.title) });
    it(`Switch(1/0, 1, 8, 2, 9)`, function() { roundtrip(this.test.title) });
    it(`Switch(1, 1/0, 2, 1, 3)`, function() { roundtrip(this.test.title) });
  });

  describe('TableMathfuncs', function() {
    it(`IsBlank(Sum(Filter([1,2,3],Value > 10), Value))`, function() { roundtrip(this.test.title) });
    it(`Sum([1,2,3], Value)`, function() { roundtrip(this.test.title) });
    it(`Sum(LastN([1, 2, 3, 4, 5], Blank()), Value)`, function() { roundtrip(this.test.title) });
    it(`Sum(Sort([-2, -1, 0, 1, 2], 1 / Value), Value)`, function() { roundtrip(this.test.title) });
    it(`Sum(1, 2, 3, Blank(), 2, 3)`, function() { roundtrip(this.test.title) });
    it(`Sum([1, 2, 1/0, 4, 5], Value)`, function() { roundtrip(this.test.title) });
    it(`Min([1, 2, 3, 4, 5], Value)`, function() { roundtrip(this.test.title) });
    it(`Min([1, 2, 1/0, 4, 5], Value)`, function() { roundtrip(this.test.title) });
    it(`Min(1, 2, 3, Blank(), 2, 3)`, function() { roundtrip(this.test.title) });
    it(`Max([1, 2, 3, 4, 5], Value)`, function() { roundtrip(this.test.title) });
    it(`Max([1, 2, 1/0, 4, 5], Value)`, function() { roundtrip(this.test.title) });
    it(`Max(1, 2, 3, Blank(), 2, 3)`, function() { roundtrip(this.test.title) });
    it(`IsBlank(Average(Filter([1,2,3],Value > 10), Value))`, function() { roundtrip(this.test.title) });
    it(`Average([1,2,3], Value)`, function() { roundtrip(this.test.title) });
    it(`Average(LastN([1, 2, 3, 4, 5], Blank()), Value)`, function() { roundtrip(this.test.title) });
    it(`Average(Sort([-2, -1, 0, 1, 2], 1 / Value), Value)`, function() { roundtrip(this.test.title) });
    it(`Average(1, 2, 3, Blank(), 2, 2)`, function() { roundtrip(this.test.title) });
    it(`Average([1, 2, 1/0, 4, 5], Value)`, function() { roundtrip(this.test.title) });
  });

  describe('TableStringfuncs', function() {
    it(`Concatenate("a", Table({b:"1"},{b:"2"}))`, function() { roundtrip(this.test.title) });
    it(`Concatenate("a", LastN(Table({b:"1"},{b:"2"}), 0))`, function() { roundtrip(this.test.title) });
    it(`Concatenate("a", If(1<0, ["txt"]))`, function() { roundtrip(this.test.title) });
    it(`Concatenate("a", If(1/0<2, ["txt"]))`, function() { roundtrip(this.test.title) });
    it(`Concatenate("a", ["hello", Mid("great", -1), "world"])`, function() { roundtrip(this.test.title) });
    it(`Concatenate("a", Table({a:"one"},If(1<0,{a:"two"}),{a:"three"}))`, function() { roundtrip(this.test.title) });
    it(`Concatenate("a", Table({a:"one"},If(1/0<2,{a:"two"}),{a:"three"}))`, function() { roundtrip(this.test.title) });
    it(`Concatenate(Blank(), ["hello", Mid("great", -1), "world"])`, function() { roundtrip(this.test.title) });
    it(`Concatenate(Blank(), Table({a:"one"},If(1<0,{a:"two"}),{a:"three"}))`, function() { roundtrip(this.test.title) });
    it(`Concatenate(Blank(), Table({a:"one"},If(1/0<2,{a:"two"}),{a:"three"}))`, function() { roundtrip(this.test.title) });
    it(`Concatenate(Table({b:"1"},{b:"2"}), "a")`, function() { roundtrip(this.test.title) });
    it(`Concatenate(LastN(Table({b:"1"},{b:"2"}), 0), "a")`, function() { roundtrip(this.test.title) });
    it(`Concatenate(If(1<0, ["txt"]), "a")`, function() { roundtrip(this.test.title) });
    it(`Concatenate(If(1/0<2, ["txt"]), "a")`, function() { roundtrip(this.test.title) });
    it(`Concatenate(["hello", Mid("great", -1), "world"], "a")`, function() { roundtrip(this.test.title) });
    it(`Concatenate(Table({a:"one"},If(1<0,{a:"two"}),{a:"three"}), "a")`, function() { roundtrip(this.test.title) });
    it(`Concatenate(Table({a:"one"},If(1/0<2,{a:"two"}),{a:"three"}), "a")`, function() { roundtrip(this.test.title) });
    it(`Concatenate(["hello", Mid("great", -1), "world"], Blank())`, function() { roundtrip(this.test.title) });
    it(`Concatenate(Table({a:"one"},If(1<0,{a:"two"}),{a:"three"}), Blank())`, function() { roundtrip(this.test.title) });
    it(`Concatenate(Table({a:"one"},If(1/0<2,{a:"two"}),{a:"three"}), Blank())`, function() { roundtrip(this.test.title) });
    it(`Concatenate(["one", "two"], [1, 2, 3, 4])`, function() { roundtrip(this.test.title) });
    it(`Concatenate(["one", "two"], LastN(Table({b:"1"},{b:"2"}), 0))`, function() { roundtrip(this.test.title) });
    it(`Concatenate(["one", "two"], If(1<0, ["txt"]))`, function() { roundtrip(this.test.title) });
    it(`Concatenate(["one", "two"], If(1/0<2, ["txt"]))`, function() { roundtrip(this.test.title) });
    it(`Concatenate(["one", "two"], Table({a:"one"},If(1<0,{a:"two"}),{a:"three"}))`, function() { roundtrip(this.test.title) });
    it(`Concatenate(["one", "two"], ["hello", Mid("great", -1), "world"])`, function() { roundtrip(this.test.title) });
    it(`Concatenate(["a","b","c","d"], "-", ["1", "2"], "-", ["x", "y", "z"], "!")`, function() { roundtrip(this.test.title) });
  });

  describe.skip('Testing', function() {
  });

  describe('Text', function() {
    it(`Text(123)`, function() { roundtrip(this.test.title) });
    it(`Text(123.4)`, function() { roundtrip(this.test.title) });
    it(`Text(10*10)`, function() { roundtrip(this.test.title) });
    it(`Text(1/2)`, function() { roundtrip(this.test.title) });
    it(`Text(123.4, "#.000")`, function() { roundtrip(this.test.title) });
    it(`Text(Blank(), "#.000")`, function() { roundtrip(this.test.title) });
    it(`Text(123.4, Blank())`, function() { roundtrip(this.test.title) });
    it(`Text(1/0, "#.000")`, function() { roundtrip(this.test.title) });
    it(`Text(0.5, ".##")`, function() { roundtrip(this.test.title) });
    it(`Text(1.5, "000")`, function() { roundtrip(this.test.title) });
    it(`Text(123456789, "#,#")`, function() { roundtrip(this.test.title) });
    it(`Text(123456789, "#,###")`, function() { roundtrip(this.test.title) });
    it(`Text(123456789, "0,0.0")`, function() { roundtrip(this.test.title) });
    it(`Text(123456789, "0,00.0")`, function() { roundtrip(this.test.title) });
    it(`Text(123456789, "0,")`, function() { roundtrip(this.test.title) });
    it(`Text(100, "#%‰'eE:")`, function() { roundtrip(this.test.title) });
    it(`Text(567, "!#!#!#!#!")`, function() { roundtrip(this.test.title) });
    it(`Text(true)`, function() { roundtrip(this.test.title) });
    it(`Text(false)`, function() { roundtrip(this.test.title) });
    it(`Text("abc")`, function() { roundtrip(this.test.title) });
    it(`Char(65)`, function() { roundtrip(this.test.title) });
    it(`Char(Blank())`, function() { roundtrip(this.test.title) });
    it(`Char(660/10)`, function() { roundtrip(this.test.title) });
    it(`Char(1/0)`, function() { roundtrip(this.test.title) });
    it(`Text(Date(2018, 3, 15), "yyyy-MM-dd")`, function() { roundtrip(this.test.title) });
    it(`Text(Date(2018, 3, 15), "MM-dd-yyyy")`, function() { roundtrip(this.test.title) });
  });

  describe('Time', function() {
    it(`Text(Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Hour(Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Minute(Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Second(Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Text(Time(Blank(), 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Time(1/0, 2, 3)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,15) < Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,15) < Time(8,1,15)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,15) <= Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,15) <= Time(8,1,15)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,30) < Time(8,1,15)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,30) <= Time(8,1,15)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,15) > Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,15) > Time(8,1,15)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,15) >= Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,15) >= Time(8,1,15)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,30) > Time(8,1,15)`, function() { roundtrip(this.test.title) });
    it(`Time(8,1,30) >= Time(8,1,15)`, function() { roundtrip(this.test.title) });
    it(`Time(Blank(), 2, 3) < Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(Blank(), 2, 3) <= Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(Blank(), 2, 3) > Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(Blank(), 2, 3) >= Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(1/0, 2, 3) < Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(1/0, 2, 3) <= Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(1/0, 2, 3) > Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Time(1/0, 2, 3) >= Time(8,1,30)`, function() { roundtrip(this.test.title) });
    it(`Text(Time(10, 70, 360))`, function() { roundtrip(this.test.title) });
    it(`Text(Time(10, -30, 360))`, function() { roundtrip(this.test.title) });
    it(`Text(Time(10, 30, -360))`, function() { roundtrip(this.test.title) });
    it(`Text(Time(10, -30, -360))`, function() { roundtrip(this.test.title) });
    it(`Year(Date(2011, 2, 3) + Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Month(Date(2011, 2, 3) + Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Day(Date(2011, 2, 3) + Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Hour(Date(2011, 2, 3) + Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Minute(Date(2011, 2, 3) + Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Second(Date(2011, 2, 3) + Time(1, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Year(Time(1, 2, 3) + Date(2011, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Month(Time(1, 2, 3) + Date(2011, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Day(Time(1, 2, 3) + Date(2011, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Hour(Time(1, 2, 3) + Date(2011, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Minute(Time(1, 2, 3) + Date(2011, 2, 3))`, function() { roundtrip(this.test.title) });
    it(`Second(Time(1, 2, 3) + Date(2011, 2, 3))`, function() { roundtrip(this.test.title) });
  });

  describe('Value', function() {
    it(`Value("-5")`, function() { roundtrip(this.test.title) });
    it(`Value("5")`, function() { roundtrip(this.test.title) });
    it(`Value("0")`, function() { roundtrip(this.test.title) });
    it(`Value("0.0")`, function() { roundtrip(this.test.title) });
    it(`Value("123,456.78")`, function() { roundtrip(this.test.title) });
    it(`Value("xxx")`, function() { roundtrip(this.test.title) });
    it(`Value("")`, function() { roundtrip(this.test.title) });
    it(`Value(1/0)`, function() { roundtrip(this.test.title) });
    it(`IsError(Value(""))`, function() { roundtrip(this.test.title) });
    it(`Value(Blank())`, function() { roundtrip(this.test.title) });
    it(`Value( "$ 12.34" )`, function() { roundtrip(this.test.title) });
    it(`Value( "24e3" )`, function() { roundtrip(this.test.title) });
    it(`Value( "12.34%" )`, function() { roundtrip(this.test.title) });
    it(`Value("%")`, function() { roundtrip(this.test.title) });
    it(`IsError(Value("%"))`, function() { roundtrip(this.test.title) });
    it(`Value(" %10")`, function() { roundtrip(this.test.title) });
    it(`Value("10% ")`, function() { roundtrip(this.test.title) });
    it(`Value("%10")`, function() { roundtrip(this.test.title) });
    it(`Value("1%00")`, function() { roundtrip(this.test.title) });
    it(`Value("$10%")`, function() { roundtrip(this.test.title) });
    it(`Value(123)`, function() { roundtrip(this.test.title) });
    it(`Value(Date(1900, 1, 1))`, function() { roundtrip(this.test.title) });
    it(`Value(Date(1900, 2, 28))`, function() { roundtrip(this.test.title) });
    it(`Value(Date(1900, 3, 1))`, function() { roundtrip(this.test.title) });
    it(`Value(Date(1900, 3, 1)) - Value(Date(1900, 2, 28))`, function() { roundtrip(this.test.title) });
  });

  describe('Weekday', function() {
    it(`Weekday(Date(2020,7,16))`, function() { roundtrip(this.test.title) });
    it(`WeekNum(Date(2019,1,6))`, function() { roundtrip(this.test.title) });
    it(`ISOWeekNum(Date(2019,1,6))`, function() { roundtrip(this.test.title) });
  });

  describe('With', function() {
    it(`With(Blank(), Blank())`, function() { roundtrip(this.test.title) });
    it(`With( {y : 3} , y*y)`, function() { roundtrip(this.test.title) });
    it(`With({x : 5}, With({ x : x*2}, x))`, function() { roundtrip(this.test.title) });
    it(`With(First(First(LastN(ForAll(Table({Value:1}, {Value:0}, {Value:2}), Table({a: 1/ThisRecord.Value})), 2)).Value), a * a)`, function() { roundtrip(this.test.title) });
  });

});
